import { useEffect, useRef, useState } from "react";
import { ArrowRight, ArrowUpRight, BatteryCharging, Buildings, CheckCircle, Database, Gauge, Lightning, List, ShieldCheck, X, Plus, Minus } from "./icons";
import { pageMeta, legacyRoutes, pageContent, insightItems, faqs } from "./content";
import { AssessmentPage } from "./Assessment";
import { ButtonLink, trackEvent } from "./ui";

const navItems = [["Data Centers", "/data-centers"], ["Platform", "/platform"], ["90-Day Pilot", "/pilot"], ["DER Partners", "/partners"], ["About", "/about"]];
const assets = "/assets/";
const route = () => window.location.pathname.replace(/\/$/, "").replace(/^\/preview\.html$/, "") || "/";

function Header({ path }) {
  const [open, setOpen] = useState(false);
  const trigger = useRef(null), header = useRef(null);
  useEffect(() => {
    if (!open) return;
    const close = e => { if (e.key === "Escape") { setOpen(false); trigger.current?.focus(); } };
    const outside = e => { if (!header.current?.contains(e.target)) setOpen(false); };
    const media = matchMedia("(min-width: 1051px)");
    const resized = () => { if (media.matches) setOpen(false); };
    document.addEventListener("keydown", close); document.addEventListener("pointerdown", outside); media.addEventListener("change", resized);
    return () => { document.removeEventListener("keydown", close); document.removeEventListener("pointerdown", outside); media.removeEventListener("change", resized); };
  }, [open]);
  const links = navItems.map(([label, href]) => <a key={href} href={href} aria-current={path === href ? "page" : undefined}>{label}</a>);
  return <header className="site-header" ref={header}><div className="container header-inner"><a className="wordmark" href="/" aria-label="EcoXchange home">Eco<span>X</span>change</a><nav className="desktop-nav" aria-label="Primary navigation">{links}</nav><a className="button button--primary header-cta" href="/assessment" aria-current={path === "/assessment" ? "page" : undefined} onClick={() => trackEvent("assessment_cta", { source: "header" })}>Assess your power gap<ArrowUpRight aria-hidden="true" /></a><button className="menu-button" ref={trigger} aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <List />}</button></div><nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation" hidden={!open}>{links}<ButtonLink href="/assessment">Assess your power gap</ButtonLink></nav></header>;
}
function Footer() {
  return <footer className="footer"><div className="container footer-lead"><div><p className="eyebrow">Start with one real power gap</p><h2>Make the MW/time gap clear.</h2><p>Required load, firm supply, timing, and the next deployable step.</p></div><ButtonLink href="/assessment" variant="signal" onClick={() => trackEvent("assessment_cta", { source: "footer" })}>Assess your power gap</ButtonLink></div><div className="container footer-grid"><div className="footer-brand"><a href="/" className="wordmark">EcoXchange</a><p>Distributed power infrastructure<br />for data centers.</p></div><div><h3>Explore</h3>{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div><div><h3>Connect</h3><a href="/assessment">Power-gap assessment</a><a href="/pilot">90-day DER pilot</a><a href="/financeability">Deployment financing</a><a href="/case-studies">Field patterns</a><a href="/contact">Contact</a><a href="/faq">FAQ</a></div><div><h3>Information</h3><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/accessibility">Accessibility</a></div></div><div className="container footer-bottom"><span>© 2026 EcoXchange</span><span>Identify. Connect. Verify. Aggregate.</span></div></footer>;
}
function ConsentBanner() {
  const [visible, setVisible] = useState(() => { try { return !localStorage.getItem("ecoxchange-analytics"); } catch { return true; } });
  if (!visible) return null;
  const choose = value => { try { localStorage.setItem("ecoxchange-analytics", value); } catch { /* The choice lasts for this page when storage is blocked. */ } setVisible(false); };
  return <section className="consent" aria-label="Analytics preference"><p><strong>Your privacy, your choice.</strong> Allow optional performance analytics to help improve this site. <a href="/privacy">Privacy details</a></p><div><button onClick={() => choose("essential")}>Essential only</button><button onClick={() => choose("granted")}>Allow analytics</button></div></section>;
}

const outcomes = [[Gauge, "A quantified bridge requirement", "Compare required firm load with effective firm supply on the same ramp date, then define the duration and reliability duty."], [BatteryCharging, "A dependable DER stack", "Match generation, storage, flexible demand, and distributed renewables to the actual constrained interval."], [ShieldCheck, "A pilot and rollout path", "Define the telemetry, partners, controls, financing needs, and operating evidence required to move from analysis into deployment."]];
const capabilities = [["Power-gap discovery", "Required MW, secured firm MW, power-arrival date, ramp date, and the resulting bridge requirement.", "/data-centers"], ["Demand-to-supply matching", "Engineer a credible stack using effective firm capacity, usable MWh, flexible demand, and operating constraints.", "/platform"], ["Deployment & financing assembly", "Coordinate technology, integration, market-access, and capital partners when the physical solution requires them.", "/financeability"], ["Telemetry & orchestration", "Preserve availability, response, duration, and verified value as the fleet grows toward coordinated dispatch.", "/platform"]];
function ProcessList({ items }) {
  return <ol className="process-list">{items.map(([title, copy], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol>;
}
function PowerGapEquation() {
  return <section className="power-gap-band" aria-labelledby="power-gap-equation-title"><div className="container"><p className="eyebrow">The core equation</p><div className="power-gap-equation"><div className="equation-term"><strong id="power-gap-equation-title">Required Firm Load MW</strong><span>What must be live at the ramp milestone</span></div><span className="equation-operator" aria-hidden="true">−</span><div className="equation-term"><strong>Effective Firm Supply MW</strong><span>What is physically dependable by that same date</span></div><span className="equation-operator" aria-hidden="true">=</span><div className="equation-term equation-term--result"><strong>Net Bridge Requirement MW</strong><span>The shortfall that still needs a solution</span></div></div><p className="power-gap-caption">Then convert the MW gap into a duty profile: start date, duration, hours per day, response time, redundancy, recharge or fuel requirements, and exit date.</p></div></section>;
}
function HomePage() {
  return <>
    <section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Distributed power infrastructure for data centers</p><h1>Close the power gap before it slows your <span>ramp.</span></h1><p className="hero-summary">EcoXchange identifies the real MW/time shortfall, matches it with dependable distributed energy, coordinates the partners needed to deploy it, and builds the evidence layer for commercial orchestration.</p><div className="hero-actions"><ButtonLink href="/assessment" variant="signal" onClick={() => trackEvent("assessment_cta", { source: "hero" })}>Assess your power gap</ButtonLink><a className="text-link" href="/platform">See the operating model<ArrowUpRight aria-hidden="true" /></a></div><p className="hero-note">Required MW → firm MW → power date → ramp date → bridge requirement.</p></div><figure className="hero-visual"><img src={`${assets}ecoxchange-switchgear-hero.webp`} alt="Data-center electrical switchgear with copper busbars" fetchPriority="high" /><figcaption><Lightning aria-hidden="true" /><span>Built around real infrastructure.</span></figcaption></figure></div></section>
    <PowerGapEquation />
    <section className="section outputs-section"><div className="container"><div className="section-heading split-heading"><div><p className="eyebrow">What the first review should answer</p><h2>A real gap, a credible bridge,<br className="desktop-break" /> and a path to deployment.</h2></div><p>Start with one site and one ramp milestone. Separate what is requested or announced from what is physically available and dependable.</p></div><div className="outcome-grid">{outcomes.map(([Icon, title, copy], i) => <article key={title}><div className="card-top"><Icon aria-hidden="true" /><span>0{i + 1}</span></div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section process-section"><div className="container process-grid"><figure className="campus-visual"><img src={`${assets}ecoxchange-campus-aerial.webp`} alt="Data-center campus and electrical substation at dusk" loading="lazy" /><figcaption>One site. A complete operating picture.</figcaption></figure><div><p className="eyebrow">How it works</p><h2>From power gap<br className="desktop-break" /> to operating capacity.</h2><ProcessList items={[["Discover the gap", "Compare required firm MW with physically available firm supply on each ramp date."], ["Engineer the bridge", "Match dependable generation, storage, flexible load, and distributed renewables to the duty profile."], ["Assemble the deployment", "Coordinate technology, integration, market-access, and financing partners where they are required."], ["Pilot and scale", "Validate telemetry, operating logic, and value before expanding into a larger commercial fleet."]]} /><a href="/platform" className="text-link">Explore all six stages<ArrowRight aria-hidden="true" /></a></div></div></section>
    <section className="section capabilities-section"><div className="container"><div className="section-heading split-heading"><div><p className="eyebrow">Connected capabilities</p><h2>The physical, commercial,<br className="desktop-break" /> and operating picture together.</h2></div><p>Keep the MW/time requirement at the center while resource, capital, telemetry, and market-access workstreams move around it.</p></div><div className="capability-grid">{capabilities.map(([title, copy, href], i) => <a href={href} className="capability-card" key={title}><span className="item-number">0{i + 1}</span><h3>{title}</h3><p>{copy}</p><ArrowUpRight aria-hidden="true" /></a>)}</div><div className="audience-grid">{[[Buildings, "Data-center teams", "Quantify the power gap", "/data-centers"], [BatteryCharging, "DER & project partners", "Match dependable capacity", "/partners"], [Database, "Market & capital partners", "Enable deployment", "/financeability"]].map(([Icon, title, copy, href]) => <a href={href} key={title}><Icon aria-hidden="true" /><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight aria-hidden="true" /></a>)}</div></div></section>
  </>;
}
function SystemDiagram() {
  return <figure className="system-diagram"><img src={`${assets}ecoxchange-capacity-system.webp`} width={1891} height={832} alt="Flexible load and onsite energy resources connect through telemetry to verified capacity." loading="lazy" /><figcaption><ol>{[["Flexible load", "Define critical and movable demand."], ["Onsite resources", "Match storage and generation to need."], ["Telemetry", "Connect source-labeled operating data."], ["Verified capacity", "Measure availability and performance."]].map(([title, copy]) => <li key={title}><strong>{title}</strong><span>{copy}</span></li>)}</ol></figcaption></figure>;
}
function StandardPage({ content, path }) {
  const explanatory = ["/platform", "/financeability", "/pilot"].includes(path);
  return <><section className={`standard-hero ${explanatory ? "standard-hero--light" : "standard-hero--dark"}`}><div className="container standard-grid"><div><p className="eyebrow">{content.eyebrow}</p><h1>{content.title}</h1><p className="lead">{content.summary}</p><ButtonLink href={content.action[1]} variant={explanatory ? "primary" : "signal"}>{content.action[0]}</ButtonLink></div>{explanatory ? <div className="hero-system"><p className="eyebrow">The connected operating picture</p><SystemDiagram /></div> : <img className="standard-image" src={content.image} alt={path === "/data-centers" ? "Data-center campus at dusk" : "Electrical switchgear and energy infrastructure"} />}</div></section><section className="summary-strip"><div className="container summary-grid">{content.stats.map(([title, copy]) => <div key={title}><CheckCircle aria-hidden="true" /><div><h2>{title}</h2><p>{copy}</p></div></div>)}</div></section><section id="workflow" className="section"><div className="container narrative-grid"><div><p className="eyebrow">The operating model</p><h2>From possibility<br className="desktop-break" /> to operable capacity.</h2><p className="muted">Readiness comes before orchestration. Make the assumptions, boundaries, and next actions clear.</p></div><ProcessList items={content.sections} /></div></section>{!explanatory && <section className="section diagram-section"><div className="container"><div className="section-heading"><p className="eyebrow">Connected evidence</p><h2>One system. Every constraint visible.</h2></div><SystemDiagram /></div></section>}<div className="container related-links"><a className="text-link" href="/faq">Questions about the process?<ArrowRight aria-hidden="true" /></a><a className="text-link" href={path === "/financeability" ? "/partners" : "/financeability"}>{path === "/financeability" ? "Explore partner pathways" : "Explore deployment financing"}<ArrowUpRight aria-hidden="true" /></a></div></>;
}
function EditorialHero({ eyebrow, title, children }) { return <section className="editorial-hero container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children && <p className="lead">{children}</p>}</section>; }
function InsightsPage() { return <><EditorialHero eyebrow="Insights" title="Power systems, made legible.">Field notes and technical perspectives on data-center power gaps, distributed resources, telemetry, and orchestration.</EditorialHero><section className="container insight-list" aria-label="Insights">{insightItems.map((item, i) => <article key={item.title}><span className="item-number">0{i + 1}</span><div><p className="eyebrow">{item.type}</p><h2>{item.title}</h2><p>{item.excerpt}</p></div></article>)}</section></>; }
function CaseStudiesPage() {
  return <><section className="case-hero"><div className="container standard-grid"><div><p className="eyebrow">Illustrative field patterns</p><h1>Evidence before claims.</h1><p className="lead">These illustrative scenarios show the kinds of power constraints EcoXchange is designed to clarify. They are not customer case studies.</p></div><img className="standard-image" src={`${assets}ecoxchange-campus-aerial.webp`} alt="Data-center campus at dusk" /></div></section><section className="container case-grid section">{[["AI / HPC campus", "Utility energization trails the compute deployment plan.", "Map flexible workloads, contracted capacity, storage options, and the next utility action."], ["Colocation expansion", "A new hall needs capacity without weakening customer commitments.", "Separate critical load from movable load and define firm operating boundaries."], ["Storage partner", "A battery project needs a credible demand match and telemetry plan.", "Evaluate duration, interconnection limits, financeability, and performance evidence."]].map(([title, problem, outcome], i) => <article key={title}><span className="item-number">0{i + 1}</span><h2>{title}</h2><h3>Constraint</h3><p>{problem}</p><h3>Readiness work</h3><p>{outcome}</p></article>)}</section></>;
}
function FAQPage() {
  const [open, setOpen] = useState(0);
  return <><EditorialHero eyebrow="Frequently asked questions" title="A clearer starting point.">What EcoXchange does, who it serves, and what to expect from an assessment.</EditorialHero><section className="container faq-list" aria-label="Frequently asked questions">{faqs.map(([q, a], i) => <article key={q}><h2><button id={`question-${i}`} aria-controls={`answer-${i}`} aria-expanded={open === i} onClick={() => setOpen(open === i ? -1 : i)}><span>{q}</span>{open === i ? <Minus aria-hidden="true" /> : <Plus aria-hidden="true" />}</button></h2><div id={`answer-${i}`} role="region" aria-labelledby={`question-${i}`} hidden={open !== i}><p>{a}</p></div></article>)}</section><p className="container legal-note">Informational and decision-support platform. An assessment does not guarantee interconnection, energization, dispatch, market participation, utility savings, or financing.</p></>;
}
function AboutPage() { return <><EditorialHero eyebrow="About EcoXchange" title="Distributed power infrastructure for data centers.">Data centers can be ready to ramp before enough utility power is physically available. EcoXchange identifies that MW/time gap, matches it with dependable distributed energy, coordinates deployment and financing partners, verifies performance, and is building the software layer to optimize those resources as virtual capacity.</EditorialHero><section className="container principles section" aria-label="Our role">{[["Start with the power problem", "Required firm load, effective firm supply, timing, and reliability define the opportunity."], ["Coordinate the physical solution", "Generation, storage, flexible demand, distributed renewables, controls, market access, and financing are assembled around the same duty profile."], ["Build the evidence layer", "Telemetry and source-labeled performance data make availability, response, duration, and value reviewable as the fleet grows."], ["Orchestrate in sequence", "Readiness and deployment come before commercial optimization and VPP expansion through appropriate market-access partners."]].map(([title, copy], i) => <article key={title}><span className="item-number">0{i + 1}</span><h2>{title}</h2><p>{copy}</p></article>)}</section></>; }
function ContactPage() { return <div className="container contact-page"><div><p className="eyebrow">Contact</p><h1>Bring one real MW/time constraint.</h1><p className="lead">For a data-center power gap, start with the structured assessment. For dependable DER capacity, market access, deployment capital, or integration partnerships, start a direct conversation.</p></div><div className="contact-links"><a href="/assessment"><span className="eyebrow">Data-center operator or developer</span><h2>Assess the power gap</h2><p>Required MW, firm supply, power timing, ramp timing, and site constraints.</p><ArrowUpRight aria-hidden="true" /></a><a href="mailto:contact@ecoxchange.net?subject=EcoXchange%20DER%20partner%20inquiry"><span className="eyebrow">DER or technology partner</span><h2>Bring dependable capacity</h2><p>contact@ecoxchange.net</p><ArrowUpRight aria-hidden="true" /></a><a href="mailto:contact@ecoxchange.net?subject=EcoXchange%20deployment%20partnership"><span className="eyebrow">Market or capital partner</span><h2>Enable a deployment</h2><p>Connect around screened enterprise power needs.</p><ArrowUpRight aria-hidden="true" /></a></div></div>; }
const legalCopy = {
  "/privacy": ["Privacy", "EcoXchange collects business contact and project information that you choose to submit. It is used to respond to inquiries, evaluate potential engagements, secure the service, and improve the website. Optional performance analytics are enabled only when you allow them."],
  "/terms": ["Terms", "Website information is general decision support and does not create a utility, financing, brokerage, interconnection, market-participation, or savings commitment."],
  "/accessibility": ["Accessibility", "EcoXchange is designed to support keyboard navigation, visible focus, reduced motion, and responsive layouts. If you encounter an accessibility barrier, please tell us which page and feature you were using so we can help."],
};
function LegalPage({ content }) { return <section className="container legal-page"><p className="eyebrow">EcoXchange information</p><h1>{content[0]}</h1><p className="lead">{content[1]}</p><p>For questions, contact <a href="mailto:contact@ecoxchange.net">contact@ecoxchange.net</a>.</p></section>; }
function NotFound() { return <section className="container not-found"><p className="eyebrow">Page not found · 404</p><h1>Let's get you back on track.</h1><p className="lead">This page may have moved, or the address may be incorrect.</p><ButtonLink href="/">Return home</ButtonLink></section>; }

export function App() {
  const path = route();
  useEffect(() => {
    if (legacyRoutes[path]) { window.location.replace(legacyRoutes[path]); return; }
    const [title, description] = pageMeta[path] || [legalCopy[path] ? `${legalCopy[path][0]} — EcoXchange` : "Page not found — EcoXchange", "Distributed power infrastructure for data centers."];
    document.title = title;
    for (const [selector, value] of [['meta[name="description"]', description], ['meta[property="og:title"]', title], ['meta[property="og:description"]', description]]) document.querySelector(selector)?.setAttribute("content", value);
    let canonical = document.querySelector('link[rel="canonical"]');
    if (!canonical) { canonical = document.createElement("link"); canonical.rel = "canonical"; document.head.appendChild(canonical); }
    canonical.href = `https://www.ecoxchange.net${path === "/" ? "" : path}`;
    const structured = document.createElement("script"); structured.id = "structured-data"; structured.type = "application/ld+json";
    const graph = [{ "@type": "Organization", name: "EcoXchange", url: "https://www.ecoxchange.net", email: "contact@ecoxchange.net" }, { "@type": "Service", name: "Power-Gap Assessment", provider: { "@type": "Organization", name: "EcoXchange" }, areaServed: "United States", description: "Power-gap discovery, technical audit, distributed-energy matching, and pilot readiness for data centers." }];
    if (path === "/faq") graph.push({ "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) });
    structured.textContent = JSON.stringify({ "@context": "https://schema.org", "@graph": graph }); document.head.appendChild(structured); return () => structured.remove();
  }, [path]);
  let page;
  if (path === "/") page = <HomePage />; else if (pageContent[path]) page = <StandardPage content={pageContent[path]} path={path} />; else if (path === "/insights") page = <InsightsPage />; else if (path === "/case-studies") page = <CaseStudiesPage />; else if (path === "/about") page = <AboutPage />; else if (path === "/faq") page = <FAQPage />; else if (path === "/assessment") page = <AssessmentPage />; else if (path === "/contact") page = <ContactPage />; else if (legalCopy[path]) page = <LegalPage content={legalCopy[path]} />; else page = <NotFound />;
  return <><a className="skip-link" href="#main-content">Skip to content</a><Header path={path} /><main id="main-content" tabIndex={-1}>{page}</main><Footer /><ConsentBanner /></>;
}

