export const pageMeta = {
  "/": ["EcoXchange — Make every usable megawatt visible", "Power-flexibility readiness and distributed-energy infrastructure for data centers."],
  "/data-centers": ["Data Centers — EcoXchange", "Understand the flexible power, onsite resources, and operating constraints at a data-center site."],
  "/partners": ["DER & Project Partners — EcoXchange", "Bring distributed-energy assets into a measurable data-center power network."],
  "/platform": ["Platform — EcoXchange", "From site readiness through telemetry, verification, aggregation, and future orchestration."],
  "/financeability": ["Project Finance Readiness — EcoXchange", "Make capital requirements and financing constraints visible before deployment."],
  "/case-studies": ["Field Notes — EcoXchange", "Illustrative operating patterns for data-center power flexibility."],
  "/insights": ["Insights — EcoXchange", "Clear thinking on data-center power, distributed resources, telemetry, and verification."],
  "/about": ["About — EcoXchange", "Building the operating layer that makes flexible power measurable."],
  "/faq": ["FAQ — EcoXchange", "Answers about power-flexibility readiness, distributed resources, and VPP orchestration."],
  "/assessment": ["Power Flexibility Assessment — EcoXchange", "Start with one real site and establish what usable capacity exists."],
  "/contact": ["Contact — EcoXchange", "Discuss a data-center power constraint or distributed-energy asset."],
};

export const legacyRoutes = {
  "/market": "/platform", "/develop": "/partners", "/verification": "/platform",
  "/method": "/platform", "/bankability": "/financeability", "/invest": "/financeability",
};

export const pageContent = {
  "/data-centers": { eyebrow: "For data-center operators and developers", title: "Know how much power flexibility your site can use.", summary: "EcoXchange separates utility service, contracted obligations, critical load, flexible compute, onsite resources, and market constraints—before expansion plans depend on capacity that is not real.", image: "/assets/ecoxchange-campus-aerial.webp", action: ["Start a site assessment", "/assessment"], stats: [["Flexible MW", "Bounded by workload and operating requirements"], ["DER capacity", "Storage and generation matched to site need"], ["Market pathway", "Utility, tariff, and partner rules made visible"]], sections: [["Start with the constraint", "A structured review maps planned and contracted MW, energization limits, critical-load boundaries, workload flexibility, onsite resources, and tariff context."], ["Return an operating picture", "The output identifies potential flexible capacity, firm boundaries, distributed-resource options, telemetry requirements, and the next utility or technical action."], ["Build from one site", "As verified resources grow, the same evidence model can support aggregation and coordinated operation through qualified partners."]] },
  "/partners": { eyebrow: "For DER, storage, generation, and project partners", title: "Bring energy assets into a data-center power network.", summary: "Evaluate whether a distributed resource can support a real data-center need, what it takes to deploy, and what operating evidence will be required.", image: "/assets/ecoxchange-switchgear-hero.webp", action: ["Discuss an energy asset", "/contact"], stats: [["Finance", "Surface capital needs and constraints"], ["Connect", "Define the telemetry that proves capacity"], ["Match", "Align asset characteristics to site demand"]], sections: [["Identify the asset", "Start with storage, generation, renewable energy, or another distributed resource tied to a credible site need."], ["Assess financeability", "Model project economics, indicative debt capacity, sponsor-equity requirements, and the capital needed to bring the resource online."], ["Verify the operating fit", "Confirm MW, duration, response characteristics, interconnection context, and the measurements required for performance verification."]] },
  "/platform": { eyebrow: "How EcoXchange works", title: "Turn fragmented power resources into measurable capacity.", summary: "The operating model joins data-center load, distributed-energy assets, and the evidence required to deploy, measure, and eventually coordinate them.", image: "/assets/ecoxchange-switchgear-hero.webp", action: ["Explore the workflow", "#workflow"], stats: [["Load", "Critical and flexible MW"], ["Assets", "Storage, generation, and DERs"], ["Evidence", "Telemetry, availability, and performance"]], sections: [["Identify", "Map the load, utility service, distributed resources, and operating constraints."], ["Finance", "Assess the capital required to deploy storage, generation, or other resources where needed."], ["Connect & verify", "Integrate operating data and measure availability, response, duration, and performance with source provenance."], ["Aggregate & orchestrate", "Combine qualified capacity and build toward coordinated dispatch through the applicable utility or market-partner pathway."]] },
  "/financeability": { eyebrow: "Project finance readiness", title: "Make the capital requirement visible before deployment.", summary: "Estimate indicative debt capacity, sponsor-equity requirements, tax-credit value, and the financing constraints that shape a distributed-energy project.", image: "/assets/ecoxchange-campus-aerial.webp", action: ["Discuss a project", "/contact"], stats: [["Cash flow", "Debt sized to project economics"], ["Capital gap", "Sponsor equity shown after permanent sources"], ["Scenarios", "Assumptions and constraints compared clearly"]], sections: [["Debt sized to cash flow", "Compare DSCR-sized debt with the applicable loan-to-cost ceiling rather than relying on a generic leverage percentage."], ["Sponsor equity made explicit", "Keep permanent debt and modeled tax-credit proceeds separate before calculating remaining sponsor capital."], ["Explainable analysis", "Preserve the scenario, assumptions, binding constraints, calculation version, and next financing action for review."]] },
};

export const insightItems = [
  { type: "Field note", title: "Why a megawatt is not a megawatt", excerpt: "Location, response time, duration, dispatch rights, tariff treatment, and evidence determine whether capacity is useful." },
  { type: "Perspective", title: "Readiness before orchestration", excerpt: "The first product is a defensible operating picture—not a premature claim that a virtual power plant already exists." },
  { type: "Technical brief", title: "The evidence layer for flexible power", excerpt: "Availability, production, response, and duration become more valuable when their sources remain traceable." },
];

export const faqs = [["What is EcoXchange building?", "Distributed power infrastructure that helps data centers quantify flexible load, evaluate onsite resources, connect operating data, and verify usable capacity."], ["Is EcoXchange already a virtual power plant?", "No. EcoXchange is building toward aggregation and orchestration. The current starting point is site readiness, evidence, and a qualified operating pathway."], ["Who is the best fit today?", "AI/HPC, colocation, and data-center development sites where grid timing, contracted MW, or power infrastructure limits deployment or growth."], ["What inputs are needed for an assessment?", "Planned MW, utility context, load profile, critical-load boundaries, target energization date, and existing or planned onsite resources."], ["Does EcoXchange sell electricity?", "Not through this website. The applicable utility, retail, wholesale, and market roles depend on jurisdiction and may be performed through qualified partners."], ["What role does verification play?", "Verification keeps availability, production, response, duration, and performance tied to source-labeled operating evidence."]];

