import { useCompliance } from "../ComplianceProvider.js";
import { EngineHealth } from "../../components/EngineHealth.js";

const TEXT = "font-mono text-[10px] leading-[1.6] tracking-[0.01em] text-textMuted";

const MODE_LABEL = {
  demo: "Demonstration Platform",
  preview: "Investor Preview",
  live: "Regulated Securities Platform",
} as const;

/**
 * Page-level legal disclaimer footer: †/‡ legend, mode-specific disclaimer
 * blocks (from disclaimerConfig.ts — counsel edits one file), engine/data
 * attribution, and platform identification. Rendered on every shell page.
 */
export function DisclaimerFooter() {
  const { mode, disclaimers } = useCompliance();

  return (
    <footer className="mt-12 border-t border-darkBg/10 pt-6 pb-8">
      <div className="mx-auto max-w-[1200px]">
        {/* Disclosure symbols legend */}
        <div>
          <p className={TEXT}>
            † All return and yield figures are {disclaimers.yieldBasis} and do
            not represent a guarantee of future performance. Past performance
            is not indicative of future results.
          </p>
          <p className={`${TEXT} mt-1`}>
            ‡ Forward-looking statements are subject to risks and uncertainties
            and may differ materially from actual results.
          </p>
        </div>

        {/* Mode-specific disclaimer blocks */}
        <div className="mt-4 border-t border-darkBg/10 pt-4">
          {disclaimers.blocks.map((block, i) => (
            <p key={i} className={`${TEXT} mt-2 first:mt-0`}>
              {block}
            </p>
          ))}
        </div>

        {/* Data source and engine attribution */}
        <div className="mt-4 border-t border-darkBg/10 pt-4">
          <p className={TEXT}>
            Production estimates generated by EcoXchange's proprietary
            verification engine (v2.0.0) using pvlib ModelChain. Irradiance
            data sourced from NASA POWER API and NREL NSRDB. All figures are
            methodology-documented estimates unless otherwise noted. Engine
            methodology documentation available upon request.
          </p>
        </div>

        {/* Platform identification + settlement-chain heartbeat */}
        <div className="mt-4 flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <span className={`${TEXT} !text-medGreen`}>EcoXchange</span>
            <span className={TEXT}>·</span>
            <span className={TEXT}>{MODE_LABEL[mode]}</span>
          </div>
          {/* The chain heartbeat (live block height + TESTNET badge) used to
              sit here, on every page. Settlement plumbing is not a site-wide
              status line — it now lives inside the portfolio's ownership-record
              section, next to what it actually describes. */}
          <div className="flex items-center gap-4">
            <EngineHealth />
          </div>
        </div>
      </div>
    </footer>
  );
}
