// Page 1: cover + executive summary.

import type { VerificationReportModel } from "../report-utils/report-model.js";
import {
  ReportDisclaimer,
  ReportPage,
  ReportSectionHeader,
  ReportStatBand,
  ReportTermRow,
} from "../report-components/ReportChrome.js";
import { formatUsd } from "../../utils/formatters.js";

export function ReportCoverPage({
  model,
  page,
  total,
}: {
  model: VerificationReportModel;
  page: number;
  total: number;
}) {
  return (
    <ReportPage page={page} total={total} withHeader={false}>
      {/* Cover header bar */}
      <div className="-mx-12 -mt-12 mb-8 bg-darkBg px-12 py-8">
        <div className="flex items-center gap-2">
          <span className="inline-block h-3.5 w-3.5 bg-accentBrt" aria-hidden />
          <span className="font-heading text-lg italic text-cream">
            EcoXchange
          </span>
        </div>
        <h1 className="mt-4 font-heading text-[28px] italic leading-tight text-white">
          Production Verification Report
        </h1>
        <p className="mt-1 font-mono text-[11px] text-lightGreen">
          {model.projectName} · {model.sourceBadge} · Run {model.reportId}
        </p>
      </div>

      <ReportSectionHeader>PROJECT SUMMARY</ReportSectionHeader>
      <dl>
        <ReportTermRow label="Project" value={model.projectName} />
        <ReportTermRow label="Location" value={model.locationLabel} />
        <ReportTermRow
          label="Nameplate DC"
          value={`${model.capacityKwDc.toLocaleString("en-US")} kW`}
        />
        <ReportTermRow
          label="Configuration"
          value={`${model.tiltDeg}° tilt · ${model.azimuthDeg}° azimuth`}
        />
        <ReportTermRow
          label="Module Eff / System Losses"
          value={`${model.moduleEfficiencyPct.toFixed(0)}% · ${model.systemLossesPct.toFixed(0)}%`}
        />
        <ReportTermRow
          label="Offtake"
          value={
            model.stateProgram
              ? `${model.offtakeLabel} (${model.stateProgram})`
              : model.offtakeLabel
          }
        />
        {model.ppaRate != null ? (
          <ReportTermRow
            label="PPA Rate"
            value={`$${model.ppaRate.toFixed(3)}/kWh${
              model.ppaEscalatorPct != null
                ? ` · ${model.ppaEscalatorPct.toFixed(1)}%/yr escalator`
                : ""
            }`}
          />
        ) : null}
      </dl>

      <div className="mt-8">
        <ReportStatBand
          items={[
            {
              value: `${Math.round(model.annualMwh).toLocaleString("en-US")} MWh`,
              label: "Annual Est.",
            },
            {
              value: `${model.capacityFactorPct.toFixed(1)}%`,
              label: "Cap Factor",
            },
            {
              value: `~${formatUsd(model.annualRevenueUsd)}`,
              label: "Est. Annual Rev",
            },
            { value: model.engineVersion, label: "Engine" },
          ]}
        />
      </div>

      <ReportSectionHeader>ANALYSIS PERIOD</ReportSectionHeader>
      <dl>
        <ReportTermRow
          label="Backtest Window"
          value={model.backtestWindowLabel}
        />
        <ReportTermRow
          label="Irradiance Data"
          value="NASA POWER (0.5° × 0.5° resolution)"
        />
        <ReportTermRow
          label="Physics Model"
          value={`pvlib ModelChain ${model.engineVersion}`}
        />
        <ReportTermRow label="Data Source" value={model.sourceBadge} />
        <ReportTermRow
          label="Report Generated"
          value={model.reportDateLabel}
        />
      </dl>

      <div className="mt-8">
        <ReportDisclaimer>
          This report was generated by EcoXchange's proprietary verification
          engine using satellite irradiance data. Revenue figures are modeled
          estimates, not contracted amounts. This document does not constitute
          an investment recommendation or offering.
        </ReportDisclaimer>
      </div>
    </ReportPage>
  );
}
