// Page 4: capital formation comparison + next steps + full disclaimer.

import type { VerificationReportModel } from "../report-utils/report-model.js";
import {
  ReportDisclaimer,
  ReportPage,
  ReportSectionHeader,
} from "../report-components/ReportChrome.js";
import { ReportHorizontalBars } from "../report-components/ReportHorizontalBars.js";
import { ReportCostTable } from "../report-components/ReportCostTable.js";
import { SPEC_COST } from "../../utils/cost-comparison.js";
import { formatUsd } from "../../utils/formatters.js";

export function ReportCostPage({
  model,
  page,
  total,
}: {
  model: VerificationReportModel;
  page: number;
  total: number;
}) {
  const scaleMax = SPEC_COST.traditionalHighUsd;
  const firstYearSavingsLow =
    SPEC_COST.traditionalLowUsd - model.allInYear1Usd;
  const firstYearSavingsHigh =
    SPEC_COST.traditionalHighUsd - model.allInYear1Usd;

  return (
    <ReportPage page={page} total={total}>
      <ReportSectionHeader>
        CAPITAL FORMATION: TRADITIONAL VS. ECOXCHANGE
      </ReportSectionHeader>

      <ReportHorizontalBars
        rows={[
          {
            label: "Traditional Reg D 506(c) — First Year",
            valueLabel: `${formatUsd(SPEC_COST.traditionalLowUsd)}–${formatUsd(SPEC_COST.traditionalHighUsd)}`,
            widthPct: (SPEC_COST.traditionalLowUsd / scaleMax) * 100,
            fillClass: "bg-gray-400",
            rangeWidthPct:
              ((SPEC_COST.traditionalHighUsd - SPEC_COST.traditionalLowUsd) /
                scaleMax) *
              100,
          },
          {
            label: "EcoXchange — First Year",
            valueLabel: `${formatUsd(model.cost.ecoxchangeTotal)} + ${formatUsd(SPEC_COST.ecoxchangeAnnualUsd)}/yr`,
            widthPct: (model.cost.ecoxchangeTotal / scaleMax) * 100,
            fillClass: "bg-medGreen",
          },
        ]}
      />
      <p className="mt-2 border-l-2 border-accentBrt bg-paleGreen/20 px-3 py-1.5 font-mono text-[10px] text-darkBg">
        FIRST-YEAR SAVINGS: {formatUsd(firstYearSavingsLow)}–
        {formatUsd(firstYearSavingsHigh)}
      </p>

      <div className="mt-5">
        <ReportCostTable model={model} />
      </div>

      {/* Next steps card */}
      <div className="mt-6 border-l-4 border-accentBrt bg-white py-3 pl-4 pr-3">
        <h3 className="font-heading text-[15px] italic text-darkBg">
          § Next Steps
        </h3>
        <p className="mt-1.5 text-[10.5px] leading-relaxed text-textDark">
          If these numbers work for your project, the next step is a
          non-binding Letter of Intent. The LOI signals your interest in
          listing this project on EcoXchange when the platform launches.
        </p>
        <ul className="mt-2 list-disc space-y-0.5 pl-4 text-[10.5px] text-textDark">
          <li>The LOI is non-binding and costs you nothing</li>
          <li>No exclusive commitment required</li>
          <li>Pre-filled from your project data</li>
        </ul>
        <p className="mt-2.5 font-mono text-[10px] text-darkBg">
          Contact: Mikal Banks · mikal@ecoxchange.net · demo.ecoxchange.net
        </p>
      </div>

      <div className="mt-6">
        <ReportDisclaimer>
          This report is generated by EcoXchange's proprietary verification
          engine for informational purposes only. Expected generation
          estimates are based on satellite irradiance data and standard solar
          physics models; actual production may vary due to site-specific
          conditions, equipment performance, weather variability, and other
          factors. This report does not constitute an investment
          recommendation, securities offering, or guarantee of future
          performance. All investor-facing materials require review by
          securities counsel before distribution.
          <br />
          <br />
          Powered by EcoXchange Verification Engine {model.engineVersion} ·
          Target three-source architecture: inverter telemetry · utility meter
          data · satellite irradiance
        </ReportDisclaimer>
      </div>
    </ReportPage>
  );
}
