-- 001_savannah_backtest.sql
-- Seeds the Savannah 5MW Community Solar project plus its 12 verification
-- records from the engine v2.0.0 backtest (pvlib ModelChain). Monthly
-- INV→EXP deviations carry realistic noise (±2–5%) rather than an artificial
-- 0.0%; the annual inverter total still reconciles to the expected total.
-- Regenerated by ecoxchange-dashboard/scripts/generate-realistic-seed.mjs.

INSERT INTO projects (
    id, name, latitude, longitude, timezone,
    capacity_kw_dc, tilt_deg, azimuth_deg,
    module_efficiency, system_losses, degradation_rate,
    commissioning_date, inverter_brand, inverter_api_key_ref, inverter_plant_id,
    offtake_type, ppa_rate_per_kwh, ppa_escalator, status
) VALUES (
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'Savannah Community Solar 5MW',
    32.08, -81.09, 'America/New_York',
    5000, 20, 180,
    0.20, 0.14, 0.0075,
    '2023-01-01', 'solaredge', 'demo-key-ref', 'demo-plant-001',
    'community_solar', 0.085, 0.02, 'active'
);

INSERT INTO verification_records (
    project_id, period_start, period_end,
    inverter_kwh, utility_kwh, expected_kwh,
    inv_vs_expected_pct, inv_vs_utility_pct, util_vs_expected_pct,
    status, flag_reasons, tolerance_config, estimated_revenue, engine_version
) VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-01-01', '2024-01-31', 512270, 490863, 516016, -0.73, 4.36, -4.87, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 43543, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-02-01', '2024-02-29', 557180, 537876, 546624, 1.93, 3.59, -1.6, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 47360, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-03-01', '2024-03-31', 642064, 611372, 667163, -3.76, 5.02, -8.36, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 54575, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-04-01', '2024-04-30', 830626, 782627, 836859, -0.74, 6.13, -6.48, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 70603, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-05-01', '2024-05-31', 781984, 762872, 796045, -1.77, 2.51, -4.17, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 66469, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-06-01', '2024-06-30', 826402, 803219, 858953, -3.79, 2.89, -6.49, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 70244, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-07-01', '2024-07-31', 823000, 798060, 795158, 3.5, 3.13, 0.36, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 69955, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-08-01', '2024-08-31', 777430, 762896, 776243, 0.15, 1.91, -1.72, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 66082, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-09-01', '2024-09-30', 630109, 603422, 611196, 3.09, 4.42, -1.27, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 53559, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-10-01', '2024-10-31', 736676, 721005, 721974, 2.04, 2.17, -0.13, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 62617, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-11-01', '2024-11-30', 483396, 471818, 486701, -0.68, 2.45, -3.06, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 41089, '2.0.0'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-12-01', '2024-12-31', 501618, 494143, 489823, 2.41, 1.51, 0.88, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 42638, '2.0.0');
