-- 001_savannah_backtest.sql
-- Seeds the Savannah 5MW Community Solar project, its twelve verification
-- records, the readings underneath them, and the engine run that produced
-- them. Regenerated by ecoxchange-dashboard/scripts/generate-realistic-seed.mjs.
--
-- Spec 19. The satellite irradiance is real NASA POWER data for these exact
-- coordinates. The inverter and utility legs are SIMULATED — every row is
-- stamped data_provenance = 'simulated' and no surface may render these
-- numbers without that tag.
--
-- Series composition (Spec 19 §3.2): 11 VERIFIED, 1 FLAGGED
-- (2024-09-01 at -18.4% INV→EXP), and 2024-11-01
-- carrying no utility reading, which exercises the two-way degrade path.
--
-- The project is seeded 'suspended', not 'active': it holds simulated
-- telemetry and must not be picked up by any job iterating active projects
-- (Spec 19 Task A, migration 013).

INSERT INTO projects (
    id, name, latitude, longitude, timezone,
    capacity_kw_dc, tilt_deg, azimuth_deg,
    module_efficiency, system_losses, degradation_rate,
    commissioning_date, inverter_brand, inverter_api_key_ref, inverter_plant_id,
    offtake_type, ppa_rate_per_kwh, ppa_escalator, status
) VALUES (
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'Savannah Community Solar 5MW',
    32.08, -81.09, 'America/New_York',
    5000, 20, 180,
    0.20, 0.14, 0.0075,
    '2023-01-01', 'solaredge', 'demo-key-ref', 'demo-plant-001',
    'community_solar', 0.085, 0.02, 'suspended'
);

INSERT INTO engine_runs (
    engine_version, target_period, trigger_type, completed_at,
    projects_attempted, projects_verified, projects_flagged
) VALUES (
    '2.0.0', '2024-12-31', 'backtest', now(),
    1, 1, 1
);

INSERT INTO raw_readings (
    project_id, source, period_start, period_end,
    kwh_gross, kwh_net, ghi_kwh_m2,
    raw_response, data_quality, data_provenance
) VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-01-01', '2024-01-31', NULL, NULL, 93.7, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-01-01', '2024-01-31', 515456, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-01-01', '2024-01-31', NULL, 490817, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-02-01', '2024-02-29', NULL, NULL, 106.7, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-02-01', '2024-02-29', 560645, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-02-01', '2024-02-29', NULL, 528247, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-03-01', '2024-03-31', NULL, NULL, 140.5, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-03-01', '2024-03-31', 666314, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-03-01', '2024-03-31', NULL, 650029, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-04-01', '2024-04-30', NULL, NULL, 185.5, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-04-01', '2024-04-30', 827190, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-04-01', '2024-04-30', NULL, 803985, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-05-01', '2024-05-31', NULL, NULL, 184.9, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-05-01', '2024-05-31', 829043, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-05-01', '2024-05-31', NULL, 803920, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-06-01', '2024-06-30', NULL, NULL, 203.1, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-06-01', '2024-06-30', 865616, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-06-01', '2024-06-30', NULL, 849434, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-07-01', '2024-07-31', NULL, NULL, 186.8, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-07-01', '2024-07-31', 824862, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-07-01', '2024-07-31', NULL, 789926, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-08-01', '2024-08-31', NULL, NULL, 174.6, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-08-01', '2024-08-31', 796977, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-08-01', '2024-08-31', NULL, 780024, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-09-01', '2024-09-30', NULL, NULL, 131.3, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-09-01', '2024-09-30', 498736, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-09-01', '2024-09-30', NULL, 486790, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-10-01', '2024-10-31', NULL, NULL, 140.2, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-10-01', '2024-10-31', 743957, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-10-01', '2024-10-31', NULL, 732870, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-11-01', '2024-11-30', NULL, NULL, 90, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-11-01', '2024-11-30', 481775, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'satellite', '2024-12-01', '2024-12-31', NULL, NULL, 87, '{"source":"nasa_power","irradiance_is_real":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'inverter', '2024-12-01', '2024-12-31', 492184, NULL, NULL, '{"simulated":true}', 'complete', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'utility_meter', '2024-12-01', '2024-12-31', NULL, 478314, NULL, '{"simulated":true}', 'complete', 'simulated');

INSERT INTO verification_records (
    project_id, period_start, period_end,
    inverter_kwh, utility_kwh, expected_kwh,
    inv_vs_expected_pct, inv_vs_utility_pct, util_vs_expected_pct,
    status, flag_reasons, tolerance_config, estimated_revenue, engine_version,
    data_provenance
) VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-01-01', '2024-01-31', 515456, 490817, 516016, -0.11, 4.78, -4.88, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 43814, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-02-01', '2024-02-29', 560645, 528247, 546624, 2.57, 5.78, -3.36, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 47655, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-03-01', '2024-03-31', 666314, 650029, 667163, -0.13, 2.44, -2.57, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 56637, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-04-01', '2024-04-30', 827190, 803985, 836859, -1.16, 2.81, -3.93, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 70311, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-05-01', '2024-05-31', 829043, 803920, 796045, 4.15, 3.03, 0.99, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 70469, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-06-01', '2024-06-30', 865616, 849434, 858953, 0.78, 1.87, -1.11, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 73577, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-07-01', '2024-07-31', 824862, 789926, 795158, 3.74, 4.24, -0.66, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 70113, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-08-01', '2024-08-31', 796977, 780024, 776243, 2.67, 2.13, 0.49, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 67743, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-09-01', '2024-09-30', 498736, 486790, 611196, -18.4, 2.4, -20.35, 'flagged', '{"Inverter production 18.4% BELOW expected (threshold: -15%). Possible causes: panel degradation exceeding model, soiling, shading, inverter fault, curtailment.","Utility meter 20.4% BELOW expected (threshold: -20%). Possible causes: high on-site consumption, curtailment, system issue."}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 42393, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-10-01', '2024-10-31', 743957, 732870, 721974, 3.04, 1.49, 1.51, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 63236, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-11-01', '2024-11-30', 481775, NULL, 486701, -1.01, NULL, NULL, 'verified', '{"Utility meter data not available — verification based on inverter vs. satellite only (two-way check)."}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 40951, '2.0.0', 'simulated'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', '2024-12-01', '2024-12-31', 492184, 478314, 489823, 0.48, 2.82, -2.35, 'verified', '{}', '{"inv_vs_expected_upper_pct":15,"inv_vs_expected_lower_pct":-15,"inv_vs_utility_pct":10,"util_vs_expected_upper_pct":20,"util_vs_expected_lower_pct":-20,"min_data_completeness_pct":90}', 41836, '2.0.0', 'simulated');
