import type { Pool, PoolClient } from "pg";
import { pool as defaultPool } from "../../db";
import { CALCULATION_ENGINE_VERSION } from "./core";
import type { OrganizationContext, PersistedCalculationBundle } from "./calculation-service";
import type { ProjectFinanceInput } from "./domain-contracts";
import type { ProjectFinanceCoreResult, SensitivityVariable } from "./returns-downside";
import { hashCalculationResult } from "./calculation-service";
import { hashFinanceInput, SCENARIO_RESOLVER_VERSION } from "./scenario-resolver";
import { sensitivityBaseValue, sensitivityField, sensitivitySummary, type SensitivityRunBundle } from "./sensitivity-service";

export type ComputedSensitivityPoint={value:number;input:ProjectFinanceInput;result:ProjectFinanceCoreResult;isBase:boolean};

async function setTenant(client:PoolClient,context:OrganizationContext){await client.query("select set_config('app.organization_id',$1,true),set_config('app.user_id',$2,true)",[context.organizationId,context.actorUserId]);}

function mapBundle(result:ProjectFinanceCoreResult){
  const financing=result.debt.financing_summary,tax=result.capital_stack.tax_credit_result,stack=result.capital_stack.capital_stack_result,returns=result.returns,downside=result.downside;
  return {
    annual_project_cashflows:result.operating.annual_project_cash_flows.map((row,index)=>({...row,sponsor_operating_cash_flow:returns.sponsor_operating_cash_flows[index]??null,depreciation:index===0?returns.bonus_depreciation:null,tax_shield:index===0?returns.immediate_tax_shield:null})),
    annual_debt_schedules:result.debt.annual_debt_schedule,
    financing_result:{dscr_sized_debt:financing.dscr_sized_debt,ltc_debt_limit:financing.ltc_debt_limit,permanent_debt:financing.permanent_debt,binding_constraint:financing.binding_constraint,debt_to_capex:financing.debt_to_capex,minimum_dscr:financing.minimum_dscr,minimum_dscr_year:financing.minimum_dscr_year,balloon_balance:financing.balloon_balance,lender_fee:result.capital_stack.lender_fee,dsra:result.capital_stack.dsra},
    tax_credit_result:{...tax,depreciable_basis:returns.depreciable_basis,bonus_depreciation:returns.bonus_depreciation,immediate_tax_shield:returns.immediate_tax_shield},
    capital_stack_result:{project_capex:result.input.transaction_costs.project_capex,closing_costs:result.input.transaction_costs.closing_costs,lender_fee:result.capital_stack.lender_fee,dsra:result.capital_stack.dsra,other_financing_uses:result.input.transaction_costs.other_financing_uses,total_closing_uses:stack.total_closing_uses,permanent_debt:stack.permanent_debt,net_itc_proceeds:stack.net_itc_proceeds,other_permanent_sources:stack.other_sources,sponsor_equity:stack.sponsor_equity,debt_pct_total_uses:stack.permanent_debt_pct_total_uses,itc_pct_total_uses:stack.itc_proceeds_pct_total_uses,sponsor_equity_pct_total_uses:stack.sponsor_equity_pct_total_uses,other_sources_pct_total_uses:stack.other_sources_pct_total_uses??0},
    return_result:{levered_sponsor_cash_irr:returns.levered_sponsor_cash_irr.irr,levered_sponsor_cash_irr_status:returns.levered_sponsor_cash_irr.status,project_unlevered_cash_irr_before_tax_attributes:returns.project_unlevered_cash_irr_before_tax_attributes.irr,unlevered_irr_status:returns.project_unlevered_cash_irr_before_tax_attributes.status,sponsor_npv:returns.sponsor_npv,project_npv:returns.project_npv,simplified_sponsor_after_tax_irr:returns.simplified_sponsor_after_tax_irr?.irr??null,tax_module_enabled:result.input.calculation_options.tax_module_enabled,irr_warning_code:returns.levered_sponsor_cash_irr.warning??null},
    downside_result:downside?{downside_type:downside.downside_type,generation_source_type:downside.generation_source_type??null,generation_multiplier:downside.generation_multiplier??null,minimum_downside_dscr:downside.minimum_downside_dscr,minimum_downside_dscr_year:downside.minimum_downside_dscr_year,full_repayment:downside.full_repayment,repayment_year:downside.repayment_year,unrepaid_balance:downside.unrepaid_balance,interest_shortfall:downside.interest_shortfall,is_lender_grade_p90:downside.generation_source_type==="INDEPENDENT_ENGINEER_P90"}:null,
    downside_cash_sweep_rows:downside?.cash_sweep_schedule??[],
    reconciliation_result:{debt_reconciliation_difference:result.debt.reconciliation.debt_reconciliation_difference,debt_reconciled:result.debt.reconciliation.debt_reconciled,sources_uses_difference:result.capital_stack.reconciliation.sources_uses_difference,sources_uses_reconciled:result.capital_stack.reconciliation.sources_uses_reconciled},
    warnings:result.warnings,
    metric_traces:result.metric_traces,
  };
}

async function insertChild(client:PoolClient,args:{context:OrganizationContext;base:PersistedCalculationBundle;point:ComputedSensitivityPoint;variable:SensitivityVariable;baseValue:number}){
  const {context,base,point,variable,baseValue}=args,bundle=mapBundle(point.result),inputHash=hashFinanceInput(point.input),resultHash=hashCalculationResult(point.result),field=sensitivityField(variable);
  const snapshot=structuredClone(base.run.input_snapshot_json) as any;
  snapshot.finance_input=point.input;
  snapshot.provenance={...(snapshot.provenance??{}),[field]:{field_key:field,value:point.value,resolution_source:"SENSITIVITY_ENGINE",source_record_type:"SENSITIVITY_POINT",policy_default_used:false,override_used:false,metadata:{base_calculation_run_id:base.run.id,base_value:baseValue,sensitivity_variable:variable}}};
  snapshot.sensitivity={variable,base_calculation_run_id:base.run.id,base_value:baseValue,input_value:point.value};
  const inserted=await client.query(`insert into project_finance.calculation_runs(organization_id,project_id,scenario_id,status,calculation_engine_version,resolver_version,underwriting_policy_id,underwriting_policy_version,input_hash,input_snapshot_json,created_by,started_at) values($1,$2,$3,'RUNNING',$4,$5,$6,$7,$8,$9::jsonb,$10,now()) returning id`,[context.organizationId,base.run.project_id,base.run.scenario_id,CALCULATION_ENGINE_VERSION,base.run.resolver_version??SCENARIO_RESOLVER_VERSION,base.run.underwriting_policy_id,base.run.underwriting_policy_version,inputHash,JSON.stringify(snapshot),context.actorUserId]);
  const runId=inserted.rows[0].id as string;
  for(const row of bundle.annual_project_cashflows)await client.query(`insert into project_finance.annual_project_cashflows(organization_id,calculation_run_id,year,generation_mwh,ppa_price_per_mwh,revenue,opex,cfads,sponsor_operating_cash_flow,depreciation,tax_shield) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[context.organizationId,runId,row.year,row.generation_mwh,row.ppa_price_per_mwh,row.revenue,row.opex,row.cfads,row.sponsor_operating_cash_flow,row.depreciation,row.tax_shield]);
  for(const row of bundle.annual_debt_schedules)await client.query(`insert into project_finance.annual_debt_schedules(organization_id,calculation_run_id,year,opening_balance,interest,principal,debt_service,ending_balance,dscr) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[context.organizationId,runId,row.year,row.opening_balance,row.interest,row.principal,row.debt_service,row.ending_balance,row.dscr]);
  const f=bundle.financing_result;await client.query(`insert into project_finance.financing_results(organization_id,calculation_run_id,dscr_sized_debt,ltc_debt_limit,permanent_debt,binding_constraint,debt_to_capex,minimum_dscr,minimum_dscr_year,balloon_balance,lender_fee,dsra) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[context.organizationId,runId,f.dscr_sized_debt,f.ltc_debt_limit,f.permanent_debt,f.binding_constraint,f.debt_to_capex,f.minimum_dscr,f.minimum_dscr_year,f.balloon_balance,f.lender_fee,f.dsra]);
  const t=bundle.tax_credit_result;await client.query(`insert into project_finance.tax_credit_results(organization_id,calculation_run_id,eligible_basis,itc_rate,itc_face_value,transfer_price,gross_transfer_proceeds,transaction_costs,net_transfer_proceeds,depreciable_basis,bonus_depreciation,immediate_tax_shield) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[context.organizationId,runId,t.eligible_basis,t.itc_rate,t.itc_face_value,t.transfer_price,t.gross_transfer_proceeds,t.transaction_costs,t.net_transfer_proceeds,t.depreciable_basis,t.bonus_depreciation,t.immediate_tax_shield]);
  const c=bundle.capital_stack_result;await client.query(`insert into project_finance.capital_stack_results(organization_id,calculation_run_id,project_capex,closing_costs,lender_fee,dsra,other_financing_uses,total_closing_uses,permanent_debt,net_itc_proceeds,other_permanent_sources,sponsor_equity,debt_pct_total_uses,itc_pct_total_uses,sponsor_equity_pct_total_uses,other_sources_pct_total_uses) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[context.organizationId,runId,c.project_capex,c.closing_costs,c.lender_fee,c.dsra,c.other_financing_uses,c.total_closing_uses,c.permanent_debt,c.net_itc_proceeds,c.other_permanent_sources,c.sponsor_equity,c.debt_pct_total_uses,c.itc_pct_total_uses,c.sponsor_equity_pct_total_uses,c.other_sources_pct_total_uses]);
  const r=bundle.return_result;await client.query(`insert into project_finance.return_results(organization_id,calculation_run_id,levered_sponsor_cash_irr,levered_sponsor_cash_irr_status,project_unlevered_cash_irr_before_tax_attributes,unlevered_irr_status,sponsor_npv,project_npv,simplified_sponsor_after_tax_irr,tax_module_enabled,irr_warning_code) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[context.organizationId,runId,r.levered_sponsor_cash_irr,r.levered_sponsor_cash_irr_status,r.project_unlevered_cash_irr_before_tax_attributes,r.unlevered_irr_status,r.sponsor_npv,r.project_npv,r.simplified_sponsor_after_tax_irr,r.tax_module_enabled,r.irr_warning_code]);
  if(bundle.downside_result){const d=bundle.downside_result;await client.query(`insert into project_finance.downside_results(organization_id,calculation_run_id,downside_type,generation_source_type,generation_multiplier,minimum_downside_dscr,minimum_downside_dscr_year,full_repayment,repayment_year,unrepaid_balance,interest_shortfall,is_lender_grade_p90) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[context.organizationId,runId,d.downside_type,d.generation_source_type,d.generation_multiplier,d.minimum_downside_dscr,d.minimum_downside_dscr_year,d.full_repayment,d.repayment_year,d.unrepaid_balance,d.interest_shortfall,d.is_lender_grade_p90]);}
  for(const row of bundle.downside_cash_sweep_rows)await client.query(`insert into project_finance.downside_cash_sweep_rows(organization_id,calculation_run_id,year,opening_balance,downside_cfads,interest_due,cash_available,principal_paid,ending_balance,interest_shortfall) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[context.organizationId,runId,row.year,row.opening_balance,row.downside_cfads,row.interest_due,row.cash_available,row.principal_paid,row.ending_balance,row.interest_shortfall]);
  const rec=bundle.reconciliation_result;await client.query(`insert into project_finance.reconciliation_results(organization_id,calculation_run_id,debt_reconciliation_difference,debt_reconciled,sources_uses_difference,sources_uses_reconciled) values($1,$2,$3,$4,$5,$6)`,[context.organizationId,runId,rec.debt_reconciliation_difference,rec.debt_reconciled,rec.sources_uses_difference,rec.sources_uses_reconciled]);
  for(const w of bundle.warnings)await client.query(`insert into project_finance.calculation_warnings(organization_id,calculation_run_id,code,severity,message,metric_key,year,metadata_json) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[context.organizationId,runId,w.code,w.severity,w.message,w.metric_key??null,w.year??null,JSON.stringify(w.metadata??null)]);
  for(const tr of bundle.metric_traces){await client.query(`insert into project_finance.formula_registry(formula_id,formula_name,formula_version,effective_from_engine_version) values($1,$1,1,$2) on conflict(formula_id) do nothing`,[tr.formula_id,CALCULATION_ENGINE_VERSION]);await client.query(`insert into project_finance.calculation_metric_traces(organization_id,calculation_run_id,metric_key,formula_id,value_json,dependencies_json,metadata_json) values($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7::jsonb)`,[context.organizationId,runId,tr.metric_key,tr.formula_id,JSON.stringify(tr.value),JSON.stringify(tr.dependencies),JSON.stringify(tr.metadata??null)]);}
  await client.query(`update project_finance.calculation_runs set status='SUCCESS',result_hash=$3,completed_at=now() where id=$1 and organization_id=$2 and status='RUNNING'`,[runId,context.organizationId,resultHash]);
  return runId;
}

export class PostgresSensitivityRepository {
  constructor(public readonly pool:Pool=defaultPool){}
  async getScenarioState(context:OrganizationContext,scenarioId:string){const result=await this.pool.query(`select id,project_id,status from project_finance.scenarios where id=$1 and organization_id=$2`,[scenarioId,context.organizationId]);return result.rows[0]??null;}
  async persistAtomic(args:{context:OrganizationContext;base:PersistedCalculationBundle;variable:SensitivityVariable;points:ComputedSensitivityPoint[]}):Promise<SensitivityRunBundle>{
    const {context,base,variable,points}=args,client=await this.pool.connect();
    try{
      await client.query("begin");await setTenant(client,context);
      const auth=await client.query(`select s.id from project_finance.scenarios s join project_finance.projects p on p.id=s.project_id and p.organization_id=s.organization_id where s.id=$1 and p.id=$2 and s.organization_id=$3 and s.status<>'ARCHIVED' and p.archived_at is null for update of s`,[base.run.scenario_id,base.run.project_id,context.organizationId]);
      if(auth.rowCount!==1)throw new Error("TENANT_OR_SCENARIO_ACCESS_DENIED");
      const created=await client.query(`insert into project_finance.sensitivity_runs(organization_id,project_id,scenario_id,base_calculation_run_id,variable,status,created_by,created_at) values($1,$2,$3,$4,$5,'RUNNING',$6,now()) returning id,project_id,scenario_id,base_calculation_run_id,variable,status,created_at,completed_at`,[context.organizationId,base.run.project_id,base.run.scenario_id,base.run.id,variable,context.actorUserId]);
      const runId=created.rows[0].id as string,baseValue=sensitivityBaseValue((base.run.input_snapshot_json as any).finance_input,variable),summaries=[] as any[];
      for(let i=0;i<points.length;i++){const point=points[i],childId=await insertChild(client,{context,base,point,variable,baseValue});const s=sensitivitySummary(point.result,point.value,point.isBase,childId);summaries.push(s);await client.query(`insert into project_finance.sensitivity_points(organization_id,sensitivity_run_id,sequence,input_value_json,child_calculation_run_id,summary_json) values($1,$2,$3,$4::jsonb,$5,$6::jsonb)`,[context.organizationId,runId,i,JSON.stringify({value:point.value,is_base:point.isBase}),childId,JSON.stringify(s)]);}
      const done=await client.query(`update project_finance.sensitivity_runs set status='SUCCESS',completed_at=now() where id=$1 and organization_id=$2 returning id,project_id,scenario_id,base_calculation_run_id,variable,status,created_at,completed_at`,[runId,context.organizationId]);
      await client.query("commit");return{...done.rows[0],points:summaries};
    }catch(error){await client.query("rollback").catch(()=>undefined);throw error;}finally{client.release();}
  }
  async get(context:OrganizationContext,runId:string):Promise<SensitivityRunBundle>{const run=await this.pool.query(`select id,project_id,scenario_id,base_calculation_run_id,variable,status,created_at,completed_at from project_finance.sensitivity_runs where id=$1 and organization_id=$2`,[runId,context.organizationId]);if(!run.rowCount)throw new Error("SENSITIVITY_RUN_NOT_FOUND");const points=await this.pool.query(`select summary_json from project_finance.sensitivity_points where sensitivity_run_id=$1 and organization_id=$2 order by sequence`,[runId,context.organizationId]);return{...run.rows[0],points:points.rows.map(r=>r.summary_json)} as SensitivityRunBundle;}
  async list(context:OrganizationContext,scenarioId:string){return(await this.pool.query(`select r.id,r.project_id,r.scenario_id,r.base_calculation_run_id,r.variable,r.status,r.created_at,r.completed_at,(select count(*)::int from project_finance.sensitivity_points p where p.sensitivity_run_id=r.id) point_count from project_finance.sensitivity_runs r where r.organization_id=$1 and r.scenario_id=$2 order by r.created_at desc`,[context.organizationId,scenarioId])).rows;}
}
