import { useMemo, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { DashboardLayout } from "@/components/dashboard-layout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { ScopeGuard } from "@/components/project-finance-workspace";
import { pfApi } from "@/lib/project-finance-api";

export default function ProjectFinanceProjectNew(){
  const [,navigate]=useLocation(); const qc=useQueryClient();
  const [form,setForm]=useState({name:"",technology:"SOLAR_PV",state_code:"",capacity_mw_ac:"",development_status:"DEVELOPMENT",revenue_structure:"FULLY_CONTRACTED"});
  const capacity=form.capacity_mw_ac.trim()?Number(form.capacity_mw_ac):null;
  const invalid=useMemo(()=>!form.name.trim()||capacity==null||!Number.isFinite(capacity)||capacity<=0,[form.name,capacity]);
  const create=useMutation({mutationFn:()=>pfApi.createProject({name:form.name.trim(),technology:form.technology,country_code:"US",state_code:form.state_code.trim()||null,capacity_mw_ac:capacity,development_status:form.development_status,revenue_structure:form.revenue_structure}),onSuccess:async p=>{await qc.invalidateQueries({queryKey:["project-finance","projects"]});navigate(`/developer/project-finance/projects/${p.id}`)}});
  return <DashboardLayout title="Create Project" description="Start with project identity. Finance facts and scenario assumptions are entered after creation." breadcrumbs={[{label:"Project Finance",href:"/developer/project-finance/projects"},{label:"Create Project"}]}>
    <div className="mx-auto max-w-3xl space-y-5"><ScopeGuard technology={form.technology} capacity={capacity} revenueStructure={form.revenue_structure}/><Card><CardHeader><CardTitle>Project identity</CardTitle><CardDescription>V0 analysis supports U.S. fully contracted solar PV projects from 1–20 MW AC.</CardDescription></CardHeader><CardContent className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><Label htmlFor="project-name">Project name</Label><Input id="project-name" value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></div><div><Label htmlFor="technology">Technology</Label><select id="technology" className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.technology} onChange={e=>setForm(v=>({...v,technology:e.target.value}))}><option value="SOLAR_PV">Solar PV</option><option value="BATTERY_STORAGE">Battery Storage</option><option value="WIND">Wind</option><option value="HYDROGEN">Hydrogen</option></select></div><div><Label htmlFor="state">State</Label><Input id="state" placeholder="NJ" maxLength={8} value={form.state_code} onChange={e=>setForm(v=>({...v,state_code:e.target.value.toUpperCase()}))}/></div><div><Label htmlFor="capacity">Capacity (MW AC)</Label><Input id="capacity" inputMode="decimal" value={form.capacity_mw_ac} onChange={e=>setForm(v=>({...v,capacity_mw_ac:e.target.value}))}/></div><div><Label htmlFor="status">Development status</Label><select id="status" className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.development_status} onChange={e=>setForm(v=>({...v,development_status:e.target.value}))}>{["DEVELOPMENT","READY_TO_BUILD","CONSTRUCTION","OPERATING","UNKNOWN"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></div><div className="md:col-span-2"><Label htmlFor="revenue">Revenue structure</Label><select id="revenue" className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.revenue_structure} onChange={e=>setForm(v=>({...v,revenue_structure:e.target.value}))}><option value="FULLY_CONTRACTED">Fully Contracted</option><option value="PARTIALLY_CONTRACTED">Partially Contracted</option><option value="MERCHANT">Merchant</option><option value="UNKNOWN">Unknown</option></select></div><div className="md:col-span-2 flex justify-end gap-2"><Button variant="outline" onClick={()=>navigate("/developer/project-finance/projects")}>Cancel</Button><Button disabled={invalid||create.isPending} onClick={()=>create.mutate()}>{create.isPending?"Creating…":"Create Project"}</Button></div></CardContent></Card>{create.error?<Alert variant="destructive"><AlertTitle>Project could not be created</AlertTitle><AlertDescription>{(create.error as Error).message}</AlertDescription></Alert>:null}</div>
  </DashboardLayout>;
}
