import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useLocation, useParams } from "wouter";
import { DashboardLayout } from "@/components/dashboard-layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { ArrowRight, Plus } from "lucide-react";
import { ScopeGuard, ScenarioStatusBanner } from "@/components/project-finance-workspace";
import { humanize, pfApi } from "@/lib/project-finance-api";

export default function ProjectFinanceProject(){
  const {projectId=""}=useParams<{projectId:string}>(); const [,navigate]=useLocation(); const qc=useQueryClient();
  const project=useQuery({queryKey:["project-finance","project",projectId],queryFn:()=>pfApi.getProject(projectId),enabled:!!projectId});
  const facts=useQuery({queryKey:["project-finance","facts",projectId],queryFn:()=>pfApi.listFacts(projectId),enabled:!!projectId});
  const scenarios=useQuery({queryKey:["project-finance","scenarios",projectId],queryFn:()=>pfApi.listScenarios(projectId),enabled:!!projectId});
  const active=(scenarios.data??[]).filter(s=>s.status!=="ARCHIVED"); const latest=active[0];
  const underwriting=useQuery({queryKey:["project-finance","underwriting-history",latest?.id??"none"],queryFn:()=>pfApi.listUnderwritingRuns(latest!.id),enabled:!!latest?.id});
  const createBase=useMutation({mutationFn:()=>pfApi.createScenario(projectId,{name:"Base Case",scenario_type:"BASE"}),onSuccess:async s=>{await qc.invalidateQueries({queryKey:["project-finance","scenarios",projectId]});navigate(`/developer/project-finance/projects/${projectId}/scenarios/${s.id}/inputs`)}});
  const createCustom=useMutation({mutationFn:()=>pfApi.createScenario(projectId,{name:`Custom Scenario ${(scenarios.data?.length??0)+1}`,scenario_type:"CUSTOM"}),onSuccess:async s=>{await qc.invalidateQueries({queryKey:["project-finance","scenarios",projectId]});navigate(`/developer/project-finance/projects/${projectId}/scenarios/${s.id}/inputs`)}});
  if(project.isLoading)return <DashboardLayout><div className="h-64 animate-pulse rounded-lg bg-muted"/></DashboardLayout>;
  if(project.error||!project.data)return <DashboardLayout><Alert variant="destructive"><AlertTitle>Project unavailable</AlertTitle><AlertDescription>{(project.error as Error)?.message||"Project was not found."}</AlertDescription></Alert></DashboardLayout>;
  const p=project.data; const currentFacts=(facts.data??[]).filter(f=>f.is_current); const latestUw=underwriting.data?.[0];
  const cta=!active.length?{label:"Create Base Case",action:()=>createBase.mutate()}:{label:latest?.status==="STALE"?"Review Changes & Re-run":latest?.status==="CALCULATED"?"Open Underwriting Inputs":"Complete Underwriting Inputs",action:()=>navigate(`/developer/project-finance/projects/${projectId}/scenarios/${latest.id}/inputs`)};
  return <DashboardLayout title={p.name} description="Project overview and scenario workspace." breadcrumbs={[{label:"Project Finance",href:"/developer/project-finance/projects"},{label:p.name}]} actions={<Button onClick={cta.action}>{cta.label}<ArrowRight className="ml-2 h-4 w-4"/></Button>}>
    <div className="space-y-5"><ScopeGuard technology={p.technology} capacity={p.capacity_mw_ac==null?null:Number(p.capacity_mw_ac)} revenueStructure={p.revenue_structure}/>{latest?<ScenarioStatusBanner status={latest.status}/>:null}
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[["Technology",humanize(p.technology)],["Capacity",p.capacity_mw_ac==null?"Missing":`${Number(p.capacity_mw_ac)} MW AC`],["State",p.state_code||"Missing"],["Development",humanize(p.development_status)],["Latest underwriting",latestUw?.overall_status?humanize(latestUw.overall_status):"None"]].map(([k,v])=><Card key={k}><CardHeader className="pb-2"><CardDescription>{k}</CardDescription><CardTitle className="text-lg">{v}</CardTitle></CardHeader></Card>)}</div>
      <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card><CardHeader><CardTitle>Scenarios</CardTitle><CardDescription>Keep the Base Case stable and use separate scenarios for lender/custom cases.</CardDescription></CardHeader><CardContent className="space-y-3">{!active.length?<div className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">No scenarios. Create a Base Case to organize project facts and financing assumptions.</div>:active.map(s=><div key={s.id} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{s.name}</span><Badge variant="outline">{humanize(s.scenario_type)}</Badge><Badge variant={s.status==="STALE"?"secondary":"outline"}>{humanize(s.status)}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Updated {new Date(s.updated_at).toLocaleString()}</p></div><Button variant="outline" asChild><Link href={`/developer/project-finance/projects/${projectId}/scenarios/${s.id}/inputs`}>Open</Link></Button></div>)}<div className="flex flex-wrap gap-2 pt-2">{!active.some(s=>s.scenario_type==="BASE")?<Button onClick={()=>createBase.mutate()} disabled={createBase.isPending}><Plus className="mr-2 h-4 w-4"/>Create Base Case</Button>:null}<Button variant="outline" onClick={()=>createCustom.mutate()} disabled={createCustom.isPending}><Plus className="mr-2 h-4 w-4"/>Custom Scenario</Button></div></CardContent></Card>
        <div className="space-y-5"><Card><CardHeader><CardTitle>Latest analysis</CardTitle><CardDescription>Minimal historical handoff; Ticket 15 owns the full results dashboard.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm">{latestUw?<><div className="flex justify-between gap-4"><span className="text-muted-foreground">Overall underwriting</span><strong>{humanize(latestUw.overall_status)}</strong></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Policy version</span><span>{latestUw.underwriting_policy_version}</span></div><div><div className="text-muted-foreground">Calculation run</div><div className="mt-1 break-all font-mono text-xs">{latestUw.calculation_run_id}</div></div><div><div className="text-muted-foreground">Underwriting run</div><div className="mt-1 break-all font-mono text-xs">{latestUw.id}</div></div></>:<p className="text-muted-foreground">No previous analysis. Complete required inputs and run underwriting.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Project facts</CardTitle><CardDescription>Current facts are distinct from scenario assumptions and historical superseded facts.</CardDescription></CardHeader><CardContent><div className="text-3xl font-semibold">{currentFacts.length}</div><p className="text-sm text-muted-foreground">current fact records</p><div className="mt-5 space-y-2">{currentFacts.slice(0,7).map(f=><div key={f.id} className="flex items-center justify-between gap-3 text-sm"><span className="truncate">{humanize(f.field_key.split(".").pop())}</span><Badge variant="outline">{humanize(f.confidence_status)}</Badge></div>)}{currentFacts.length===0?<p className="text-sm text-muted-foreground">No project facts yet. Open a scenario to add inputs.</p>:null}</div></CardContent></Card></div></div>
    </div>
  </DashboardLayout>;
}
