import type { DeveloperBacktestReport } from "../utils/types.js";

function fmtUsd(n: number | null): string {
  if (n === null) return "—";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);
}
function fmtKwh(n: number | null): string {
  if (n === null) return "—";
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(n);
}

export function renderMarkdown(r: DeveloperBacktestReport): string {
  const hasInverter = r.summary.has_real_inverter_data;
  const lines: string[] = [];
  lines.push(`# ${r.title}`);
  lines.push("");
  lines.push(`**Project:** ${r.system.name}`);
  lines.push(`**Location:** ${r.system.location}`);
  lines.push(`**Capacity:** ${r.system.capacity_kw_dc.toLocaleString()} kW DC`);
  lines.push(`**Configuration:** ${r.system.configuration}`);
  lines.push(`**Commissioning date:** ${r.system.commissioning_date}`);
  lines.push(`**Generated:** ${r.generated_at}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(
    `Over the ${r.summary.months_tested}-month test period (${r.summary.period_tested}), the EcoXchange verification engine estimates this system would produce **${r.summary.annual_expected_mwh.toFixed(1)} MWh annually**, yielding a capacity factor of **${r.summary.capacity_factor_pct.toFixed(1)}%**.`,
  );
  lines.push("");
  if (hasInverter && r.summary.months_verified !== null) {
    lines.push(
      `Using your actual inverter production data, **${r.summary.months_verified} of ${r.summary.months_tested} months verified** within tolerance. Mean deviation from expected: ${r.summary.mean_deviation_pct?.toFixed(1) ?? "—"}%.`,
    );
    lines.push("");
  }
  if (r.financials.estimated_annual_revenue_usd !== null) {
    lines.push(
      `At your PPA rate of ${fmtUsd(r.financials.ppa_rate_per_kwh)}/kWh, estimated annual revenue is **${fmtUsd(r.financials.estimated_annual_revenue_usd)}**.`,
    );
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("## Monthly Production");
  lines.push("");
  if (hasInverter) {
    lines.push(
      "| Month | GHI (kWh/m²) | Expected (kWh) | Actual (kWh) | Deviation | Status |",
    );
    lines.push("|---|---|---|---|---|---|");
    for (const m of r.monthly) {
      lines.push(
        `| ${m.month} | ${m.ghi_kwh_m2.toFixed(1)} | ${fmtKwh(m.expected_kwh)} | ${fmtKwh(m.inverter_kwh)} | ${m.inv_vs_expected_pct?.toFixed(2) ?? "—"}% | ${m.status ?? "—"} |`,
      );
    }
  } else {
    lines.push("| Month | GHI (kWh/m²) | Expected (kWh) | Est. Revenue |");
    lines.push("|---|---|---|---|");
    for (const m of r.monthly) {
      lines.push(
        `| ${m.month} | ${m.ghi_kwh_m2.toFixed(1)} | ${fmtKwh(m.expected_kwh)} | ${fmtUsd(m.estimated_revenue_usd)} |`,
      );
    }
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## EcoXchange Cost Advantage");
  lines.push("");
  lines.push("| | Traditional Reg D | EcoXchange | Savings |");
  lines.push("|---|---|---|---|");
  const cc = r.financials.developer_cost_comparison;
  lines.push(
    `| All-in cost (Year 1, $2.5M raise) | ${cc.traditional_all_in_cost_usd} | ${cc.ecoxchange_estimated_cost_usd} | ${cc.savings_pct} |`,
  );
  lines.push(
    `| Time to capital | ${cc.time_to_capital_traditional} | ${cc.time_to_capital_ecoxchange} | — |`,
  );
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## What Happens Next");
  lines.push("");
  lines.push(`1. **Review** this report with EcoXchange`);
  lines.push(`2. **Sign** a Letter of Intent`);
  lines.push(
    `3. **EcoXchange forms** project SPV and prepares Reg D 506(c) offering`,
  );
  lines.push(`4. **Offering goes live** to pre-onboarded accredited investors`);
  lines.push("");
  lines.push(
    `**Contact:** ${r.next_steps.contact_name} — ${r.next_steps.contact_email}`,
  );
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    `*This report was generated by EcoXchange's patent-pending verification engine using ${r.summary.irradiance_source} satellite irradiance data. Expected generation figures are estimates based on standard solar physics models and do not constitute a guarantee of future production. All financial projections are estimates subject to material risk factors.*`,
  );
  return lines.join("\n");
}
