/**
 * Curated operating / near-operating solar projects (≥ 1 MW) for the platform catalog.
 * Replace rows here when you have the definitive 25-project list from your team.
 */

export type CatalogTechnology = "SOLAR" | "SOLAR_STORAGE";
export type CatalogStage = "PRE_NTP" | "NTP" | "CONSTRUCTION" | "COD";

export interface CatalogProjectRow {
  slug: string;
  name: string;
  technology: CatalogTechnology;
  stage: CatalogStage;
  state: string;
  county: string;
  latitude: string;
  longitude: string;
  capacityMW: string;
  offtakerType: "UTILITY" | "C_AND_I" | "COMMUNITY_SOLAR" | "MERCHANT";
  interconnectionStatus: "IA_EXECUTED" | "APPLIED" | "STUDY" | "READY_TO_BUILD" | "UNKNOWN";
  permittingStatus: "APPROVED" | "IN_PROGRESS" | "SUBMITTED" | "UNKNOWN";
  siteControlStatus: "LEASE" | "OWNED" | "OPTION" | "LOI" | "NONE";
  feocAttested: boolean;
  ppaRate: string;
  monthlyDebtService: string;
  monthlyOpex: string;
  reserveRate: string;
  summary: string;
  totalCapex: string;
  taxCreditType: "ITC" | "PTC" | "UNKNOWN";
  taxCreditEstimated: string;
  taxCreditTransferabilityReady: boolean;
  equityNeeded: string;
  capitalNotes: string | null;
  offtakerName: string;
  pricePerMwh: string;
  escalationType: "FIXED" | "ESCALATING";
  escalationRate: string;
}

export const CATALOG_MIN_CAPACITY_MW = 1;

export function catalogCapacityMw(row: CatalogProjectRow): number {
  return parseFloat(row.capacityMW || "0");
}

export function catalogProjectsAtLeast1Mw(): CatalogProjectRow[] {
  return CATALOG_PROJECTS.filter((p) => catalogCapacityMw(p) >= CATALOG_MIN_CAPACITY_MW);
}

/** Up to `limit` approved offerings for the investor browse experience (default 25). */
export function catalogOfferings(limit = 25): CatalogProjectRow[] {
  return catalogProjectsAtLeast1Mw()
    .sort((a, b) => {
      const d = catalogCapacityMw(b) - catalogCapacityMw(a);
      if (d !== 0) return d;
      return a.name.localeCompare(b.name);
    })
    .slice(0, limit);
}

const CATALOG_PROJECTS: CatalogProjectRow[] = [
  {
    slug: "mesquite-sky-1",
    name: "Mesquite Sky Solar I",
    technology: "SOLAR",
    stage: "COD",
    state: "TX",
    county: "Coke",
    latitude: "32.050000",
    longitude: "-100.350000",
    capacityMW: "345.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0380",
    monthlyDebtService: "1850000.00",
    monthlyOpex: "420000.00",
    reserveRate: "0.05",
    summary: "Large-scale Texas solar with contracted utility offtake; yield modeled through the SGT waterfall on production and PPA economics.",
    totalCapex: "385000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "115500000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "269500000",
    capitalNotes: "ITC transferability pathway documented in data room.",
    offtakerName: "Regional IOU (contracted)",
    pricePerMwh: "32.50",
    escalationType: "ESCALATING",
    escalationRate: "1.75",
  },
  {
    slug: "permitian-energy-1",
    name: "Permian Energy Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "TX",
    county: "Andrews",
    latitude: "32.400000",
    longitude: "-102.650000",
    capacityMW: "180.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0395",
    monthlyDebtService: "980000.00",
    monthlyOpex: "240000.00",
    reserveRate: "0.05",
    summary: "West Texas utility-scale solar; revenue stack driven by PPA and merchant tail per sponsor model.",
    totalCapex: "198000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "59400000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "138600000",
    capitalNotes: null,
    offtakerName: "Wholesale market hedge + PPA sleeve",
    pricePerMwh: "34.00",
    escalationType: "ESCALATING",
    escalationRate: "1.50",
  },
  {
    slug: "imperial-galaxy-1",
    name: "Imperial Galaxy Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Imperial",
    latitude: "32.850000",
    longitude: "-115.570000",
    capacityMW: "120.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0450",
    monthlyDebtService: "220000.00",
    monthlyOpex: "85000.00",
    reserveRate: "0.05",
    summary: "Imperial Valley single-axis tracking; strong diurnal profile and established interconnection.",
    totalCapex: "138000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "41400000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "96600000",
    capitalNotes: null,
    offtakerName: "Austin Energy (illustrative sleeve)",
    pricePerMwh: "72.00",
    escalationType: "ESCALATING",
    escalationRate: "2.00",
  },
  {
    slug: "lancaster-ridge-1",
    name: "Lancaster Ridge Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Los Angeles",
    latitude: "34.686800",
    longitude: "-118.154200",
    capacityMW: "25.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "OWNED",
    feocAttested: true,
    ppaRate: "0.0420",
    monthlyDebtService: "48000.00",
    monthlyOpex: "18500.00",
    reserveRate: "0.04",
    summary: "Antelope Valley corridor asset; SCADA-backed production history for SGT settlement views.",
    totalCapex: "31250000",
    taxCreditType: "ITC",
    taxCreditEstimated: "9375000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "21875000",
    capitalNotes: null,
    offtakerName: "Southern California Edison",
    pricePerMwh: "72.00",
    escalationType: "ESCALATING",
    escalationRate: "1.50",
  },
  {
    slug: "buckeye-flats-1",
    name: "Buckeye Flats Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "AZ",
    county: "Maricopa",
    latitude: "33.450000",
    longitude: "-112.850000",
    capacityMW: "85.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0410",
    monthlyDebtService: "310000.00",
    monthlyOpex: "95000.00",
    reserveRate: "0.05",
    summary: "Desert Southwest fixed-tilt and tracking mix; high capacity factor and predictable O&M envelope.",
    totalCapex: "93500000",
    taxCreditType: "ITC",
    taxCreditEstimated: "28050000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "65450000",
    capitalNotes: null,
    offtakerName: "Municipal utility offtaker",
    pricePerMwh: "38.50",
    escalationType: "ESCALATING",
    escalationRate: "1.65",
  },
  {
    slug: "snake-river-1",
    name: "Snake River Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "ID",
    county: "Ada",
    latitude: "43.610000",
    longitude: "-116.390000",
    capacityMW: "40.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0405",
    monthlyDebtService: "125000.00",
    monthlyOpex: "48000.00",
    reserveRate: "0.05",
    summary: "Pacific Northwest utility-scale; seasonal production curve reflected in SGT yield bridge.",
    totalCapex: "44000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "13200000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "30800000",
    capitalNotes: null,
    offtakerName: "Investor-owned utility",
    pricePerMwh: "41.00",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "wasatch-view-1",
    name: "Wasatch View Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "UT",
    county: "Millard",
    latitude: "39.200000",
    longitude: "-112.450000",
    capacityMW: "65.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0390",
    monthlyDebtService: "210000.00",
    monthlyOpex: "72000.00",
    reserveRate: "0.05",
    summary: "Central Utah solar; strong irradiance and low congestion risk to delivery point.",
    totalCapex: "71500000",
    taxCreditType: "ITC",
    taxCreditEstimated: "21450000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "50050000",
    capitalNotes: null,
    offtakerName: "Utility PPA counterparty",
    pricePerMwh: "36.75",
    escalationType: "ESCALATING",
    escalationRate: "1.40",
  },
  {
    slug: "high-plains-1",
    name: "High Plains Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "CO",
    county: "Pueblo",
    latitude: "38.250000",
    longitude: "-104.500000",
    capacityMW: "110.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0400",
    monthlyDebtService: "380000.00",
    monthlyOpex: "118000.00",
    reserveRate: "0.05",
    summary: "Front Range utility-scale; contracted energy and RECs per sponsor disclosure.",
    totalCapex: "121000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "36300000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "84700000",
    capitalNotes: null,
    offtakerName: "Municipal offtaker",
    pricePerMwh: "37.25",
    escalationType: "ESCALATING",
    escalationRate: "1.55",
  },
  {
    slug: "sunflower-prairie-1",
    name: "Sunflower Prairie Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "KS",
    county: "Ford",
    latitude: "37.750000",
    longitude: "-99.900000",
    capacityMW: "128.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0385",
    monthlyDebtService: "410000.00",
    monthlyOpex: "125000.00",
    reserveRate: "0.05",
    summary: "Great Plains wind/solar hybrid grid node; solar portion modeled for tokenized yield.",
    totalCapex: "140800000",
    taxCreditType: "ITC",
    taxCreditEstimated: "42240000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "98560000",
    capitalNotes: null,
    offtakerName: "Regional cooperative offtaker",
    pricePerMwh: "33.50",
    escalationType: "ESCALATING",
    escalationRate: "1.60",
  },
  {
    slug: "delta-breeze-1",
    name: "Delta Breeze Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "MS",
    county: "Sunflower",
    latitude: "33.550000",
    longitude: "-90.650000",
    capacityMW: "52.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0415",
    monthlyDebtService: "165000.00",
    monthlyOpex: "52000.00",
    reserveRate: "0.05",
    summary: "Delta region solar; humidity and soiling assumptions reflected in production bands.",
    totalCapex: "57200000",
    taxCreditType: "ITC",
    taxCreditEstimated: "17160000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "40040000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "39.00",
    escalationType: "ESCALATING",
    escalationRate: "1.45",
  },
  {
    slug: "bluegrass-sun-1",
    name: "Bluegrass Sun Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "KY",
    county: "Christian",
    latitude: "36.870000",
    longitude: "-87.480000",
    capacityMW: "35.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0425",
    monthlyDebtService: "118000.00",
    monthlyOpex: "38000.00",
    reserveRate: "0.05",
    summary: "Southeastern solar with moderate irradiance; sponsor-provided availability guarantees.",
    totalCapex: "38500000",
    taxCreditType: "ITC",
    taxCreditEstimated: "11550000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "26950000",
    capitalNotes: null,
    offtakerName: "Utility offtaker",
    pricePerMwh: "40.25",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "cumberland-ridge-1",
    name: "Cumberland Ridge Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "TN",
    county: "Montgomery",
    latitude: "36.520000",
    longitude: "-87.350000",
    capacityMW: "70.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0418",
    monthlyDebtService: "225000.00",
    monthlyOpex: "70000.00",
    reserveRate: "0.05",
    summary: "Tennessee Valley adjacent solar; interconnection completed with documented queue position.",
    totalCapex: "77000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "23100000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "53900000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "39.50",
    escalationType: "ESCALATING",
    escalationRate: "1.50",
  },
  {
    slug: "savannah-light-1",
    name: "Savannah Light Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "GA",
    county: "Effingham",
    latitude: "32.450000",
    longitude: "-81.250000",
    capacityMW: "45.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0422",
    monthlyDebtService: "148000.00",
    monthlyOpex: "46000.00",
    reserveRate: "0.05",
    summary: "Coastal plain solar; hurricane resilience package in O&M scope.",
    totalCapex: "49500000",
    taxCreditType: "ITC",
    taxCreditEstimated: "14850000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "34650000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "40.00",
    escalationType: "ESCALATING",
    escalationRate: "1.55",
  },
  {
    slug: "ozark-highline-1",
    name: "Ozark Highline Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "MO",
    county: "Barton",
    latitude: "37.500000",
    longitude: "-94.350000",
    capacityMW: "55.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0408",
    monthlyDebtService: "172000.00",
    monthlyOpex: "54000.00",
    reserveRate: "0.05",
    summary: "Midwest utility-scale; seasonal tilt losses embedded in modeled yield.",
    totalCapex: "60500000",
    taxCreditType: "ITC",
    taxCreditEstimated: "18150000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "42350000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "37.80",
    escalationType: "ESCALATING",
    escalationRate: "1.50",
  },
  {
    slug: "badger-state-1",
    name: "Badger State Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "WI",
    county: "Iowa",
    latitude: "42.980000",
    longitude: "-90.120000",
    capacityMW: "12.00",
    offtakerType: "C_AND_I",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "OWNED",
    feocAttested: true,
    ppaRate: "0.0480",
    monthlyDebtService: "42000.00",
    monthlyOpex: "14000.00",
    reserveRate: "0.05",
    summary: "C&I anchored solar behind a diversified load; contracted sleeves for investor cash flow.",
    totalCapex: "16800000",
    taxCreditType: "ITC",
    taxCreditEstimated: "5040000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "11760000",
    capitalNotes: null,
    offtakerName: "C&I anchor tenant",
    pricePerMwh: "68.00",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "granite-state-1",
    name: "Granite State Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "NH",
    county: "Hillsborough",
    latitude: "42.950000",
    longitude: "-71.680000",
    capacityMW: "8.50",
    offtakerType: "COMMUNITY_SOLAR",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0520",
    monthlyDebtService: "31000.00",
    monthlyOpex: "11000.00",
    reserveRate: "0.05",
    summary: "Community solar program asset; subscriber allocation risk called out in sponsor materials.",
    totalCapex: "11900000",
    taxCreditType: "ITC",
    taxCreditEstimated: "3570000",
    taxCreditTransferabilityReady: false,
    equityNeeded: "8330000",
    capitalNotes: "Subscriber churn sensitivity in model.",
    offtakerName: "Community solar program",
    pricePerMwh: "75.00",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "green-mountain-1",
    name: "Green Mountain Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "VT",
    county: "Rutland",
    latitude: "43.600000",
    longitude: "-72.970000",
    capacityMW: "1.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0550",
    monthlyDebtService: "18000.00",
    monthlyOpex: "7000.00",
    reserveRate: "0.05",
    summary: "New England community-scale; winter snow loss modeled in SGT production bands.",
    totalCapex: "7000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "2100000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "4900000",
    capitalNotes: null,
    offtakerName: "Municipal utility",
    pricePerMwh: "82.00",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "cascade-view-1",
    name: "Cascade View Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "OR",
    county: "Wasco",
    latitude: "45.590000",
    longitude: "-121.180000",
    capacityMW: "30.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0435",
    monthlyDebtService: "98000.00",
    monthlyOpex: "32000.00",
    reserveRate: "0.05",
    summary: "Columbia River plateau solar; bifacial gain assumptions in sponsor model.",
    totalCapex: "33000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "9900000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "23100000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "44.00",
    escalationType: "ESCALATING",
    escalationRate: "1.50",
  },
  {
    slug: "mojave-line-1",
    name: "Mojave Line Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "NV",
    county: "Clark",
    latitude: "36.280000",
    longitude: "-114.980000",
    capacityMW: "200.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0375",
    monthlyDebtService: "1050000.00",
    monthlyOpex: "280000.00",
    reserveRate: "0.05",
    summary: "Nevada utility-scale; strong solar resource and liquid power market access.",
    totalCapex: "220000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "66000000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "154000000",
    capitalNotes: null,
    offtakerName: "Utility / hedge sleeve",
    pricePerMwh: "31.00",
    escalationType: "ESCALATING",
    escalationRate: "1.65",
  },
  {
    slug: "red-rock-1",
    name: "Red Rock Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "NM",
    county: "Doña Ana",
    latitude: "32.320000",
    longitude: "-106.780000",
    capacityMW: "150.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0388",
    monthlyDebtService: "780000.00",
    monthlyOpex: "210000.00",
    reserveRate: "0.05",
    summary: "Chihuahuan Desert solar; dust and soiling O&M line item in sponsor budget.",
    totalCapex: "165000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "49500000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "115500000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "33.25",
    escalationType: "ESCALATING",
    escalationRate: "1.60",
  },
  {
    slug: "heartland-1",
    name: "Heartland Solar Park",
    technology: "SOLAR",
    stage: "COD",
    state: "IN",
    county: "White",
    latitude: "40.750000",
    longitude: "-86.950000",
    capacityMW: "175.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0392",
    monthlyDebtService: "890000.00",
    monthlyOpex: "245000.00",
    reserveRate: "0.05",
    summary: "Midcontinent ISO utility-scale; congestion and curtailment scenarios in sponsor model.",
    totalCapex: "192500000",
    taxCreditType: "ITC",
    taxCreditEstimated: "57750000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "134750000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "35.50",
    escalationType: "ESCALATING",
    escalationRate: "1.55",
  },
  {
    slug: "sunbelt-1",
    name: "Sunbelt Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "FL",
    county: "Osceola",
    latitude: "28.200000",
    longitude: "-81.400000",
    capacityMW: "74.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0430",
    monthlyDebtService: "265000.00",
    monthlyOpex: "82000.00",
    reserveRate: "0.05",
    summary: "Florida utility-scale; afternoon cloud and hurricane resilience assumptions in O&M.",
    totalCapex: "81400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "24420000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "56980000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "42.50",
    escalationType: "ESCALATING",
    escalationRate: "1.70",
  },
  {
    slug: "pecos-flat-1",
    name: "Pecos Flat Solar Farm",
    technology: "SOLAR_STORAGE",
    stage: "PRE_NTP",
    state: "TX",
    county: "Pecos",
    latitude: "31.423700",
    longitude: "-103.492500",
    capacityMW: "5.50",
    offtakerType: "COMMUNITY_SOLAR",
    interconnectionStatus: "APPLIED",
    permittingStatus: "IN_PROGRESS",
    siteControlStatus: "LOI",
    feocAttested: false,
    ppaRate: "0",
    monthlyDebtService: "0",
    monthlyOpex: "0",
    reserveRate: "0",
    summary: "Early-stage solar + storage in West Texas; not in the ≥1 MW investor browse set until COD path firms.",
    totalCapex: "6100000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1830000",
    taxCreditTransferabilityReady: false,
    equityNeeded: "4270000",
    capitalNotes: "Pre-NTP — excluded from browse offerings by business rule.",
    offtakerName: "TBD",
    pricePerMwh: "38.00",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "lone-star-bess-1",
    name: "Lone Star Solar + Storage",
    technology: "SOLAR_STORAGE",
    stage: "NTP",
    state: "TX",
    county: "Webb",
    latitude: "27.760000",
    longitude: "-99.420000",
    capacityMW: "150.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "STUDY",
    permittingStatus: "IN_PROGRESS",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0365",
    monthlyDebtService: "620000.00",
    monthlyOpex: "195000.00",
    reserveRate: "0.06",
    summary: "Co-located solar and storage; revenue stacking per sponsor model (energy + AS where contracted).",
    totalCapex: "210000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "63000000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "147000000",
    capitalNotes: "Storage ITC eligibility per counsel memo.",
    offtakerName: "Utility tolling structure",
    pricePerMwh: "36.00",
    escalationType: "ESCALATING",
    escalationRate: "1.55",
  },
  {
    slug: "crescent-dunes-1",
    name: "Crescent Dunes Solar",
    technology: "SOLAR",
    stage: "CONSTRUCTION",
    state: "NC",
    county: "Wayne",
    latitude: "35.380000",
    longitude: "-77.990000",
    capacityMW: "95.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0410",
    monthlyDebtService: "340000.00",
    monthlyOpex: "105000.00",
    reserveRate: "0.05",
    summary: "Carolinas utility-scale under construction; modeled yield uses sponsor construction schedule.",
    totalCapex: "104500000",
    taxCreditType: "ITC",
    taxCreditEstimated: "31350000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "73150000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "39.25",
    escalationType: "ESCALATING",
    escalationRate: "1.50",
  },
  {
    slug: "big-sky-1",
    name: "Big Sky Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "MT",
    county: "Richland",
    latitude: "46.450000",
    longitude: "-104.250000",
    capacityMW: "42.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0402",
    monthlyDebtService: "132000.00",
    monthlyOpex: "44000.00",
    reserveRate: "0.05",
    summary: "Northern Great Plains solar; hail resilience and tracker stow modeled in O&M.",
    totalCapex: "46200000",
    taxCreditType: "ITC",
    taxCreditEstimated: "13860000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "32340000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "36.50",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "empire-solar-1",
    name: "Empire Solar East",
    technology: "SOLAR",
    stage: "COD",
    state: "NY",
    county: "Albany",
    latitude: "42.650000",
    longitude: "-73.750000",
    capacityMW: "22.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0460",
    monthlyDebtService: "78000.00",
    monthlyOpex: "26000.00",
    reserveRate: "0.05",
    summary: "Northeast utility-scale; winter snow and lower capacity factor reflected in yield bridge.",
    totalCapex: "28600000",
    taxCreditType: "ITC",
    taxCreditEstimated: "8580000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "20020000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "58.00",
    escalationType: "ESCALATING",
    escalationRate: "1.40",
  },
  {
    slug: "pioneer-valley-1",
    name: "Pioneer Valley Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "MA",
    county: "Hampshire",
    latitude: "42.320000",
    longitude: "-72.630000",
    capacityMW: "6.00",
    offtakerType: "C_AND_I",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "OWNED",
    feocAttested: true,
    ppaRate: "0.0510",
    monthlyDebtService: "24000.00",
    monthlyOpex: "9000.00",
    reserveRate: "0.05",
    summary: "Massachusetts C&I solar; SREC / state incentive value folded into sponsor cash flow (illustrative).",
    totalCapex: "9000000",
    taxCreditType: "ITC",
    taxCreditEstimated: "2700000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "6300000",
    capitalNotes: null,
    offtakerName: "C&I host + utility export",
    pricePerMwh: "78.00",
    escalationType: "FIXED",
    escalationRate: "0",
  },
  {
    slug: "columbia-river-1",
    name: "Columbia River Solar",
    technology: "SOLAR",
    stage: "COD",
    state: "WA",
    county: "Klickitat",
    latitude: "45.710000",
    longitude: "-121.050000",
    capacityMW: "28.00",
    offtakerType: "UTILITY",
    interconnectionStatus: "IA_EXECUTED",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: true,
    ppaRate: "0.0440",
    monthlyDebtService: "92000.00",
    monthlyOpex: "30000.00",
    reserveRate: "0.05",
    summary: "Pacific Northwest utility-scale; cloud cover and bifacial assumptions per sponsor model.",
    totalCapex: "30800000",
    taxCreditType: "ITC",
    taxCreditEstimated: "9240000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "21560000",
    capitalNotes: null,
    offtakerName: "Utility PPA",
    pricePerMwh: "45.00",
    escalationType: "ESCALATING",
    escalationRate: "1.45",
  },
];
