import type { CatalogProjectRow } from "./catalog-projects.types.ts";

/** Canonical project rows shipped with the application. Overwrite via scripts/import-ca-listings-csv.ts after dropping a CSV under data/catalog/. */

export const CATALOG_PROJECTS: CatalogProjectRow[] = [
  {
    slug: "parcel-225-001",
    name: "Parcel 225-001",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "San Bernardino",
    latitude: "34.442408",
    longitude: "-116.306617",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 3.1080. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-225-003",
    name: "Parcel 225-003",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "San Bernardino",
    latitude: "34.683029",
    longitude: "-117.782462",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 5.0504. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-225-004",
    name: "Parcel 225-004",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.805013",
    longitude: "-116.700202",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 6.9555. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-225-005",
    name: "Parcel 225-005",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "San Bernardino",
    latitude: "34.006826",
    longitude: "-117.256858",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 8.6149. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-225-006",
    name: "Parcel 225-006",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.962392",
    longitude: "-117.070165",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 10.0320. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-225-007",
    name: "Parcel 225-007",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "San Bernardino",
    latitude: "34.000283",
    longitude: "-114.230932",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 1.7878. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-229-001",
    name: "Parcel 229-001",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.491031",
    longitude: "-117.419492",
    capacityMW: "2.12",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "7773.00",
    monthlyOpex: "3003.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "2332000",
    taxCreditType: "ITC",
    taxCreditEstimated: "699600",
    taxCreditTransferabilityReady: true,
    equityNeeded: "1632400",
    capitalNotes: "SGT score: 11.0676. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-229-003",
    name: "Parcel 229-003",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Kern",
    latitude: "35.060384",
    longitude: "-119.385355",
    capacityMW: "0.12",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "440.00",
    monthlyOpex: "170.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "132000",
    taxCreditType: "ITC",
    taxCreditEstimated: "39600",
    taxCreditTransferabilityReady: true,
    equityNeeded: "92400",
    capitalNotes: "SGT score: 2.1876. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-227-001",
    name: "Parcel 227-001",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "34.077432",
    longitude: "-114.582014",
    capacityMW: "8.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "29333.00",
    monthlyOpex: "11333.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "8800000",
    taxCreditType: "ITC",
    taxCreditEstimated: "2640000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "6160000",
    capitalNotes: "SGT score: 3.4631. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-229-004",
    name: "Parcel 229-004",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Kern",
    latitude: "34.963455",
    longitude: "-119.916729",
    capacityMW: "8.18",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "29993.00",
    monthlyOpex: "11588.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "8998000",
    taxCreditType: "ITC",
    taxCreditEstimated: "2699400",
    taxCreditTransferabilityReady: true,
    equityNeeded: "6298600",
    capitalNotes: "SGT score: 1.2322. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-231-001",
    name: "Parcel 231-001",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.687347",
    longitude: "-114.629958",
    capacityMW: "1.25",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "4583.00",
    monthlyOpex: "1771.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "1375000",
    taxCreditType: "ITC",
    taxCreditEstimated: "412500",
    taxCreditTransferabilityReady: true,
    equityNeeded: "962500",
    capitalNotes: "SGT score: 5.9571. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-231-003",
    name: "Parcel 231-003",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.606129",
    longitude: "-114.864156",
    capacityMW: "0.98",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "3593.00",
    monthlyOpex: "1388.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "1078000",
    taxCreditType: "ITC",
    taxCreditEstimated: "323400",
    taxCreditTransferabilityReady: true,
    equityNeeded: "754600",
    capitalNotes: "SGT score: 4.6603. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-233-001",
    name: "Parcel 233-001",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.513630",
    longitude: "-115.311010",
    capacityMW: "16.64",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "61013.00",
    monthlyOpex: "23573.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "18304000",
    taxCreditType: "ITC",
    taxCreditEstimated: "5491200",
    taxCreditTransferabilityReady: true,
    equityNeeded: "12812800",
    capitalNotes: "SGT score: 4.6068. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-225-002",
    name: "Parcel 225-002",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "San Bernardino",
    latitude: "34.210762",
    longitude: "-116.295095",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 4.7124. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-227-006",
    name: "Parcel 227-006",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "San Bernardino",
    latitude: "34.089354",
    longitude: "-115.764404",
    capacityMW: "3.66",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "13420.00",
    monthlyOpex: "5185.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4026000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1207800",
    taxCreditTransferabilityReady: true,
    equityNeeded: "2818200",
    capitalNotes: "SGT score: 2.0941. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-229-002",
    name: "Parcel 229-002",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Kern",
    latitude: "35.585581",
    longitude: "-117.986768",
    capacityMW: "0.25",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "917.00",
    monthlyOpex: "354.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "275000",
    taxCreditType: "ITC",
    taxCreditEstimated: "82500",
    taxCreditTransferabilityReady: true,
    equityNeeded: "192500",
    capitalNotes: "SGT score: 0.7501. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-227-002",
    name: "Parcel 227-002",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.496967",
    longitude: "-117.310349",
    capacityMW: "8.01",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "29370.00",
    monthlyOpex: "11348.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "8811000",
    taxCreditType: "ITC",
    taxCreditEstimated: "2643300",
    taxCreditTransferabilityReady: true,
    equityNeeded: "6167700",
    capitalNotes: "SGT score: 10.5668. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-227-004",
    name: "Parcel 227-004",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.630686",
    longitude: "-115.947571",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 3.9343. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-227-005",
    name: "Parcel 227-005",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.473202",
    longitude: "-114.925241",
    capacityMW: "4.00",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14667.00",
    monthlyOpex: "5667.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4400000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1320000",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3080000",
    capitalNotes: "SGT score: 6.8394. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-231-002",
    name: "Parcel 231-002",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.717971",
    longitude: "-115.258980",
    capacityMW: "2.41",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "8837.00",
    monthlyOpex: "3414.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "2651000",
    taxCreditType: "ITC",
    taxCreditEstimated: "795300",
    taxCreditTransferabilityReady: true,
    equityNeeded: "1855700",
    capitalNotes: "SGT score: 1.9839. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-231-004",
    name: "Parcel 231-004",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.859412",
    longitude: "-116.490981",
    capacityMW: "3.15",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "11550.00",
    monthlyOpex: "4463.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "3465000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1039500",
    taxCreditTransferabilityReady: true,
    equityNeeded: "2425500",
    capitalNotes: "SGT score: 2.8766. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-231-005",
    name: "Parcel 231-005",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.639278",
    longitude: "-115.037490",
    capacityMW: "0.48",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "1760.00",
    monthlyOpex: "680.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "528000",
    taxCreditType: "ITC",
    taxCreditEstimated: "158400",
    taxCreditTransferabilityReady: true,
    equityNeeded: "369600",
    capitalNotes: "SGT score: 3.1450. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-227-003",
    name: "Parcel 227-003",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "San Bernardino",
    latitude: "34.019373",
    longitude: "-114.603383",
    capacityMW: "4.03",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14777.00",
    monthlyOpex: "5709.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4433000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1329900",
    taxCreditTransferabilityReady: true,
    equityNeeded: "3103100",
    capitalNotes: "SGT score: 5.1202. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-231-006",
    name: "Parcel 231-006",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.663978",
    longitude: "-115.022803",
    capacityMW: "0.28",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "1027.00",
    monthlyOpex: "397.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "308000",
    taxCreditType: "ITC",
    taxCreditEstimated: "92400",
    taxCreditTransferabilityReady: true,
    equityNeeded: "215600",
    capitalNotes: "SGT score: 3.1450. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
  {
    slug: "parcel-255-001",
    name: "Parcel 255-001",
    technology: "SOLAR",
    stage: "COD",
    state: "CA",
    county: "Riverside",
    latitude: "33.859841",
    longitude: "-117.559329",
    capacityMW: "3.85",
    offtakerType: "MERCHANT",
    interconnectionStatus: "READY_TO_BUILD",
    permittingStatus: "APPROVED",
    siteControlStatus: "LEASE",
    feocAttested: false,
    ppaRate: "0.0900",
    monthlyDebtService: "14117.00",
    monthlyOpex: "5454.00",
    reserveRate: "0.05",
    summary: "Supabase import: SGT Verified listing from Efficient Markets feed.",
    totalCapex: "4235000",
    taxCreditType: "ITC",
    taxCreditEstimated: "1270500",
    taxCreditTransferabilityReady: true,
    equityNeeded: "2964500",
    capitalNotes: "SGT score: 8.6641. Data resolution: 4km - Matched Monthly.",
    offtakerName: "Not disclosed",
    pricePerMwh: "90.00",
    escalationType: "FIXED",
    escalationRate: "0",
    listingUrl: "https://app.efficientmarkets.com/salegroup/6543",
    hideOfftakerInInvestorUi: true,
    auctionBidStatus: "SGT Verified",
  },
];

