/**
 * Spec 16 § 3.1 — Attribute Ownership Disclosure. LOCKED COPY.
 *
 * Every string in `ATTRIBUTE_OWNERSHIP_COPY` is reproduced **verbatim** from
 * `docs/specs/EcoXchange_Spec_16_REC_UX.md` § 3.1. Per § 3.1:
 *
 *   "Copy strings live in a single locked module. Changes require the same review
 *    as PPM language."
 *
 * That is this module. Do not edit these strings to fit a layout — change the
 * layout. AC 3: "Attribute copy strings are unmodifiable outside the locked
 * module; CI fails on edits without review flag."
 *
 * Why it is non-negotiable (§ 3.1): an investor who believes they hold a carbon
 * claim they do not hold is a greenwashing exposure for EcoXchange and a
 * fiduciary problem for any RIA who ever allocates.
 *
 * ─── Variant C is deliberately absent ───────────────────────────────────────
 *
 * § 3.1 defines a third variant for attributes retired on investors' behalf, and
 * marks it a future product. § 9.2 and AC 19 require that it be **absent from the
 * codebase, not merely unreachable**. Its copy is therefore not reproduced here,
 * not in a comment, and not behind a flag. `attributeOwnershipCopy()` throws if
 * asked for it. When the retirement product exists, add it then.
 */

/**
 * Spec 16 § 9.2 — the `project_rec_enrollment.attribute_ownership` enum.
 *
 * All four values are legal in the database. Only two have a copy path; see the
 * variant C note above.
 */
export const ATTRIBUTE_OWNERSHIP_VALUES = [
  "retained",
  "conveyed",
  "retired_for_investors",
  "unknown",
] as const;

export type AttributeOwnership = (typeof ATTRIBUTE_OWNERSHIP_VALUES)[number];

/** The § 3.1 variants that have copy. */
export type AttributeOwnershipVariant = "A" | "B";

export interface AttributeOwnershipCopy {
  /** § 3.1 renders this as the card heading. */
  heading: string;
  /** Leading prose, rendered before the claim. */
  body: string;
  /**
   * The mandatory claim disclosure. § 3.1 bolds this sentence in both variants;
   * it is the single sentence the entire card exists to deliver, so it is a
   * separate field rather than markup inside `body`.
   */
  claim: string;
  /** Variant A only — the sentence that follows the bolded claim. */
  claimTrailer?: string;
}

export const ATTRIBUTE_OWNERSHIP_COPY: Record<
  AttributeOwnershipVariant,
  AttributeOwnershipCopy
> = {
  // A — SPV retains and sells attributes
  A: {
    heading: "Environmental attributes",
    body: "The renewable energy certificates generated by this project are sold to third parties. Investors receive the cash proceeds from those sales as part of project revenue.",
    claim:
      "Investors in this offering do not hold, and may not claim, the renewable energy attributes of this generation.",
    claimTrailer: "The purchaser of the certificates holds that claim.",
  },
  // B — Attributes conveyed to the offtaker (bundled PPA)
  B: {
    heading: "Environmental attributes",
    body: "The renewable energy certificates generated by this project are conveyed to the power purchaser under the offtake agreement. The project receives no separate certificate revenue, and this is reflected in the projected returns.",
    claim:
      "Investors in this offering do not hold, and may not claim, the renewable energy attributes of this generation.",
  },
};

/**
 * § 3.1 variant selection, including the `unknown` fallback.
 *
 * "`attribute_ownership = 'unknown'` renders variant B and raises a build-time
 * warning. **Never render an ambiguous or absent state.**"
 *
 * The fallback is conservative on purpose: variant B is the disclosure that
 * claims *less* on the investor's behalf, so defaulting to it cannot manufacture
 * an environmental claim that does not exist. `requiresWarning` is returned
 * rather than logged here so the caller decides where the warning surfaces —
 * § 3.1's card raises it at build time.
 */
export const VARIANT_BY_OWNERSHIP: Record<
  Exclude<AttributeOwnership, "retired_for_investors">,
  AttributeOwnershipVariant
> = {
  retained: "A",
  conveyed: "B",
  unknown: "B",
};

export interface AttributeOwnershipCopyResult {
  variant: AttributeOwnershipVariant;
  copy: AttributeOwnershipCopy;
  /** True when the ownership state was `unknown` and variant B was substituted. */
  requiresWarning: boolean;
}

/**
 * Resolve the § 3.1 disclosure for an ownership state.
 *
 * Throws on `retired_for_investors`: the retirement product does not exist, so
 * there is no honest disclosure to render, and rendering nothing would violate
 * § 3.1's "never render an ambiguous or absent state." A thrown error surfaces at
 * the point the data became wrong instead of shipping a blank card.
 */
export function attributeOwnershipCopy(
  ownership: AttributeOwnership,
): AttributeOwnershipCopyResult {
  if (ownership === "retired_for_investors") {
    throw new Error(
      "Spec 16 § 3.1 variant C (attributes retired on investors' behalf) is a future " +
        "product and has no copy path in this codebase (§ 9.2, AC 19). A project was " +
        "enrolled as 'retired_for_investors' without the retirement product existing — " +
        "correct the enrollment record rather than adding the copy.",
    );
  }

  const variant = VARIANT_BY_OWNERSHIP[ownership];
  return {
    variant,
    copy: ATTRIBUTE_OWNERSHIP_COPY[variant],
    requiresWarning: ownership === "unknown",
  };
}

// ─── § 4.2 Screening gate banners ────────────────────────────────────────────

/**
 * Spec 16 § 4.2 — verbatim banner copy for the intake screening gate.
 *
 * The `conveyed` and `unknown` banners are quoted directly from § 4.2. `retained`
 * has no banner in the spec: the REC module simply becomes active.
 */
export const SCREENING_GATE_COPY = {
  conveyed:
    "Environmental attributes for this project are conveyed to your power purchaser. Certificate revenue is not available on this project. Projected returns reflect energy revenue only.",
  unknown:
    "We'll need to confirm this with your offtake agreement before modeling certificate revenue.",
} as const;

/**
 * § 4.2 / § 9.4 step 4: "Not sure" is treated as conveyed until confirmed, and
 * "the conservative default must not be softened." Exported as a named constant
 * so the intake, the enrollment write, and the § 3.1 card all read the same rule
 * rather than each re-deriving it.
 */
export const UNKNOWN_IS_TREATED_AS_CONVEYED = true;

/**
 * § 9.4 step 3 — the "which program?" select is disabled until `rec_programs`
 * (a Spec 13/14 artifact) is seeded. This exact string is the specified
 * placeholder.
 */
export const PROGRAM_SELECTION_PLACEHOLDER = "PROGRAM SELECTION PENDING REGISTRY DATA";
