import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { FinanceabilityMarginPanel, ScenarioAssumptionDiff, ScenarioComparisonTable, SensitivityHistory, SensitivityResultTable, SENSITIVITY_VARIABLE_LABELS } from "./project-finance-sensitivity";

const calc:any={run:{id:"calc",scenario_id:"s1",calculation_engine_version:"0.2.0",underwriting_policy_version:"0.1.0",input_snapshot_json:{finance_input:{revenue:{ppa_price_year_1_per_mwh:55},financing:{annual_interest_rate:.065,target_dscr:1.30,max_ltc:.70,amortization_years:18},transaction_costs:{project_capex:8000000},generation:{capacity_factor_p50:.24},tax_credit:{itc_rate:.30}},provenance:{"revenue.ppa_price_year_1_per_mwh":{resolution_source:"VERIFIED_PROJECT_FACT"},"financing.annual_interest_rate":{resolution_source:"POLICY_DEFAULT"}}}},financing_result:{permanent_debt:3364160,debt_to_capex:.4205,minimum_dscr:1.30,binding_constraint:"DSCR"},capital_stack_result:{sponsor_equity:2994969,sponsor_equity_pct_total_uses:.354,net_itc_proceeds:2097600},return_result:{levered_sponsor_cash_irr:.0244},tax_credit_result:{net_transfer_proceeds:2097600},downside_result:{minimum_downside_dscr:1.096,full_repayment:true,generation_source_type:"ILLUSTRATIVE_PERCENT_OF_P50"}};
const scenario:any={id:"s1",project_id:"p1",name:"Base Case",scenario_type:"BASE",status:"CALCULATED",latest_calculation_run_id:"calc",updated_at:"2026-09-05"};
const lender:any={...scenario,id:"s2",name:"Lender Case",scenario_type:"LENDER_CASE",latest_calculation_run_id:"calc2"};
const bundles:any[]=[{scenario,calculation:calc,underwriting:{overall_status:"PASS_WITH_CONDITIONS"}},{scenario:lender,calculation:{...calc,run:{...calc.run,id:"calc2",input_snapshot_json:{...calc.run.input_snapshot_json,finance_input:{...calc.run.input_snapshot_json.finance_input,revenue:{ppa_price_year_1_per_mwh:50}},provenance:{"revenue.ppa_price_year_1_per_mwh":{resolution_source:"SCENARIO_ASSUMPTION"}}}}},underwriting:{overall_status:"REVIEW_REQUIRED"}}];
const run:any={id:"sens",project_id:"p1",scenario_id:"s1",base_calculation_run_id:"calc",variable:"PPA_PRICE",status:"SUCCESS",points:[{input_value:55,is_base:true,child_calculation_run_id:"c55",permanent_debt:3364160,debt_to_capex:.4205,sponsor_equity:2994969,minimum_dscr:1.30,levered_sponsor_cash_irr:.0244,simplified_sponsor_after_tax_irr:null,binding_constraint:"DSCR",minimum_downside_dscr:1.096,input_hash:"a",result_hash:"b"},{input_value:60,is_base:false,child_calculation_run_id:"c60",permanent_debt:4000000,debt_to_capex:.5,sponsor_equity:2400000,minimum_dscr:1.30,levered_sponsor_cash_irr:.058,simplified_sponsor_after_tax_irr:null,binding_constraint:"DSCR",minimum_downside_dscr:1.1,input_hash:"c",result_hash:"d"}]};

describe("Ticket 17 scenario comparison and sensitivity UI",()=>{
  it("renders immutable financial metrics side by side",()=>{const html=renderToStaticMarkup(<ScenarioComparisonTable bundles={bundles}/>);expect(html).toContain("Permanent Senior Debt");expect(html).toContain("Base Case");expect(html).toContain("Lender Case");expect(html).toContain("Review Required");});
  it("shows provenance differences without causal inference",()=>{const html=renderToStaticMarkup(<ScenarioAssumptionDiff bundles={bundles}/>);expect(html).toContain("Fact");expect(html).toContain("Custom Scenario");expect(html).toContain("Ppa Price Year 1 Per Mwh");});
  it("renders dimensional financeability without a score",()=>{const html=renderToStaticMarkup(<FinanceabilityMarginPanel base={calc}/>);expect(html).toContain("Financeability Margin");expect(html).toContain("Requirement 1.30x");expect(html).toContain("No aggregate score");expect(html).not.toContain("/100");});
  it("identifies Base point and child Calculation Run drilldown",()=>{const html=renderToStaticMarkup(<SensitivityResultTable run={run} projectId="p1"/>);expect(html).toContain("Base Case");expect(html).toContain("View Detailed Model");expect(html).toContain("$3.36M");});
  it("preserves historical sensitivity labels",()=>{const html=renderToStaticMarkup(<SensitivityHistory runs={[{id:"sens",project_id:"p1",scenario_id:"s1",base_calculation_run_id:"calc",variable:"PPA_PRICE",status:"SUCCESS",created_at:"2026-09-05T12:00:00Z",point_count:5}]} onSelect={()=>{}}/>);expect(html).toContain("Sensitivity History");expect(html).toContain("PPA Price");expect(html).toContain("5 points");});
  it("exposes exactly the five approved variables",()=>expect(Object.keys(SENSITIVITY_VARIABLE_LABELS)).toEqual(["PPA_PRICE","INTEREST_RATE","PROJECT_CAPEX","CAPACITY_FACTOR","ITC_RATE"]));
});
